/**
 * Company seed list — Bangalore and Surat companies
 * Each company has: ATS info OR career_url OR website (for discovery)
 */
module.exports = [
  {
    name: 'Identixweb Limited',
    slug: 'identixweb-limited',
    website: 'https://www.identixweb.com/',
    description: 'We are Shopify experts helping over 12,000 merchants sell more and grow stronger with our apps & services since 2017.',
    industry: 'E-Commerce Development',
    employee_count: 50,
    founded_year: '2017',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2057507, longitude: 72.8448174, is_hq: true },
    ],
    careerUrl: 'https://www.identixweb.com/career',
  },
  {
    name: 'Fortunesoft IT Innovations',
    slug: 'fortunesoft-it-innovations',
    website: 'https://www.fortunesoftit.com',
    description: 'Industry-Specific, Ready To Deploy Software Solutions That Drive Results',
    industry: 'Web Design',
    employee_count: 50,
    founded_year: '2009',
    offices: [
      { city: 'Nashville', state: 'United States', latitude: 12.9342151, longitude: 77.61838, is_hq: true },
    ],
    careerUrl: 'https://www.fortunesoftit.com/careers',
  },
  {
    name: 'GeoPITS Global Pvt Ltd',
    slug: 'geopits-global-pvt-ltd',
    website: 'https://www.geopits.com/',
    description: 'Remote DBA and database solutions provider specialized in performance optimization and cloud database management across RDS, PostgreSQL, MySQL, MSSQL.',
    industry: 'Enterprise App Modernization',
    employee_count: 50,
    founded_year: '2017',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 13.0250526, longitude: 77.6590585, is_hq: true },
    ],
    careerUrl: 'https://www.geopits.com/careers',
  },
  {
    name: 'KODA Integrated Marketing Services',
    slug: 'koda-integrated-marketing-services',
    website: 'https://koda.co.in/',
    description: 'Elevate Your Digital Presence with Koda a End to End Digital Marketing Agency',
    industry: 'Content Marketing',
    employee_count: 10,
    founded_year: '2019',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.905073, longitude: 77.6509956, is_hq: true },
    ],
    careerUrl: 'https://koda.co.in/work-with-us',
  },
  {
    name: 'Tricon Infotech Private Limited',
    slug: 'tricon-infotech-private',
    website: 'https://www.triconinfotech.com',
    description: 'Partnering with success',
    industry: 'Artificial Intelligence',
    employee_count: 250,
    founded_year: '1997',
    offices: [
      { city: 'Hoboken', state: 'United States', latitude: 12.9303524, longitude: 77.6152457, is_hq: true },
    ],
    careerUrl: 'https://www.triconinfotech.com/jobs',
  },
  {
    name: 'Fusion Informatics Limited',
    slug: 'fusion-informatics',
    website: 'https://www.fusioninformatic.com/',
    description: 'An offshore software development company, with expertise in web, mobile app, and custom software development based out of India, UAE, and the USA.',
    industry: 'Web Development',
    employee_count: 10,
    founded_year: '2003',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 23.0356274, longitude: 72.5182749, is_hq: true },
    ],
    careerUrl: 'https://www.fusioninformatics.com/blog/careers',
  },
  {
    name: 'Jordies Creative Agency',
    slug: 'jordie-s-creative-agency',
    website: 'https://jordiescreativeagency.com/',
    description: 'We build brands that people understand, remember, and return to.',
    industry: 'Branding',
    employee_count: 10,
    founded_year: '2024',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9822689, longitude: 77.5483408, is_hq: true },
    ],
    careerUrl: 'https://jordiescreativeagency.com/careers',
  },
  {
    name: 'Zinavo Private Limited',
    slug: 'zinavo-private-limited',
    website: 'https://www.zinavo.com/',
    description: 'Zinavo Private Limited is a professional web design, web applcaition,web development, Mobile apps and digital marketing company based in Bangalore.',
    industry: 'Email Marketing',
    employee_count: 10,
    founded_year: '2012',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 13.0144347, longitude: 77.6480663, is_hq: true },
    ],
    careerUrl: 'https://www.zinavo.com/careers.html',
  },
  {
    name: 'Adze studio',
    slug: 'adze-studio',
    website: 'https://adzestudio.com/',
    description: 'Adze Studio is a Bangalore digital marketing company delivering performance-driven strategies for quality leads and brand growth.',
    industry: 'Branding',
    employee_count: 10,
    founded_year: '2015',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.978911, longitude: 77.643472, is_hq: true },
    ],
    careerUrl: 'https://adzestudio.com/careers',
  },
  {
    name: 'Zillion IT Solutions',
    slug: 'zillion-it-solutions',
    website: 'https://zillionit.com/',
    description: 'We build scalable, high-performance software that helps businesses innovate faster, streamline operations, and gain a competitive edge.',
    industry: 'Custom Software Development',
    employee_count: 2,
    founded_year: '2005',
    offices: [
      { city: 'Kozhikode', state: 'null', latitude: 21.139529, longitude: 72.7691824, is_hq: true },
    ],
    careerUrl: 'https://zillionit.com/career',
  },
  {
    name: 'DeepKlarity',
    slug: 'deepklarity',
    website: 'https://deepklarity.com/',
    description: 'AI Engineering Studio',
    industry: 'Progressive Web Apps',
    employee_count: 2,
    founded_year: '2018',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 21.1910656, longitude: 72.8399872, is_hq: true },
    ],
    careerUrl: 'https://deepklarity.com/careers',
  },
  {
    name: 'Adroitte',
    slug: 'adroitte',
    website: 'https://www.adroitte.com/',
    description: 'Digital Marketing & Website Development Company in Bangalore',
    industry: 'SEO',
    employee_count: 10,
    founded_year: '2010',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9381165, longitude: 77.6308618, is_hq: true },
    ],
    careerUrl: 'https://www.adroitte.com/careers',
  },
  {
    name: 'Ralecon',
    slug: 'ralecon',
    website: 'https://www.ralecon.com/',
    description: 'A Decade of Digital Excellence . We specialize in delivering ROI-based digital marketing solutions that have a high success rate for our clients.',
    industry: 'SEO',
    employee_count: 50,
    founded_year: '2012',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9889227, longitude: 77.7072524, is_hq: true },
    ],
    careerUrl: 'https://www.ralecon.com/careers',
  },
  {
    name: 'Incognito Worldwide',
    slug: 'incognito-worldwide',
    website: 'http://www.incognitoworldwide.com',
    description: 'Empower Your Brand Worldwide',
    industry: 'SEO',
    employee_count: 10,
    founded_year: '2015',
    offices: [
      { city: 'Wilmington', state: 'United States', latitude: 39.7317773, longitude: -75.5785216, is_hq: true },
    ],
    careerUrl: 'https://www.incognito.com/careers',
  },
  {
    name: 'Ralecon',
    slug: 'ralecon',
    website: 'https://www.ralecon.com/',
    description: 'A Decade of Digital Excellence . We specialize in delivering ROI-based digital marketing solutions that have a high success rate for our clients.',
    industry: 'SEO',
    employee_count: 50,
    founded_year: '2012',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9889227, longitude: 77.7072524, is_hq: true },
    ],
    careerUrl: 'https://www.ralecon.com/careers',
  },
  {
    name: 'Ekfrazo Technologies',
    slug: 'ekfrazo-technologies',
    website: 'https://ekfrazo.com/',
    description: 'Our enterprise systems help businesses cut costs by 40%, reclaim 20+ hours each week through automation, and secure operations against cyber risks.',
    industry: 'Desktop App Development',
    employee_count: 50,
    founded_year: '2015',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 13.0660382, longitude: 77.5797087, is_hq: true },
    ],
    careerUrl: 'https://ekfrazo.com/careers',
  },
  {
    name: 'SAS ONE PRIVATE LIMITED',
    slug: 'sas-one-private-limited',
    website: 'https://www.sasone.in/',
    description: 'Partner for Software, Apps &amp; Embedded Systems',
    industry: 'Web Development',
    employee_count: 50,
    founded_year: '2021',
    offices: [
      { city: 'Lucknow', state: 'null', latitude: 26.8062175, longitude: 80.9917463, is_hq: true },
    ],
    careerUrl: 'https://www.sasone.in/career',
  },
  {
    name: 'Tech Exactly',
    slug: 'tech-exactly',
    website: 'https://www.techexactly.com/',
    description: 'Helping Founders Get Their Dream App',
    industry: 'Mobile App Development',
    employee_count: 10,
    founded_year: '2017',
    offices: [
      { city: 'Kolkata', state: 'West Bengal', latitude: 22.569046, longitude: 88.435784, is_hq: true },
    ],
    careerUrl: 'https://techexactly.com/career',
  },
  {
    name: 'Mydbops',
    slug: 'mydbops',
    website: 'https://www.mydbops.com/',
    description: 'Mydbops offers expert database consulting, management, and support services tailored for PostgreSQL and MySQL environments.',
    industry: 'IT Managed',
    employee_count: 50,
    founded_year: '2015',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9659434, longitude: 77.6036997, is_hq: true },
    ],
    careerUrl: 'https://www.mydbops.com/careers',
  },
  {
    name: 'Blute Technologies Pvt Ltd',
    slug: 'blute-technologies-pvt-ltd',
    website: 'https://www.blute.co.in/',
    description: 'Blute Technologies is a IT application development services company and outsourcing partner for clients in all industries.',
    industry: 'Web Development',
    employee_count: 10,
    founded_year: '2019',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9186984, longitude: 77.5761684, is_hq: true },
    ],
    careerUrl: 'https://www.blute.co.in/careers.html',
  },
  {
    name: 'Chipsy IT Services Pvt Ltd.',
    slug: 'chipsy-information-technology-services-pvt-ltd',
    website: 'https://www.chipsyservices.com/',
    description: 'Innovating Solutions, Empowering Success.',
    industry: 'Mobile App Development',
    employee_count: 10,
    founded_year: '2012',
    offices: [
      { city: 'Udupi', state: 'null', latitude: 13.3449892, longitude: 74.7512299, is_hq: true },
    ],
    careerUrl: 'https://chipsyservices.com/careers',
  },
  {
    name: 'doodleblue Innovations',
    slug: 'doodleblue',
    website: 'http://www.doodleblue.com/',
    description: 'Digital Strategy Consulting',
    industry: 'Mobile App Development',
    employee_count: 50,
    founded_year: '2012',
    offices: [
      { city: 'Chennai', state: 'Tamil Nadu', latitude: 12.9944032, longitude: 78.9191, is_hq: true },
    ],
    careerUrl: 'https://d7e2gs85v7rx.cloudfront.net/careers',
  },
  {
    name: 'Synclovis Systems Pvt. Ltd.',
    slug: 'synclovis-systems',
    website: 'http://www.synclovis.com',
    description: 'Customized Mobile & Web Apps Development',
    industry: 'Mobile App Development',
    employee_count: 10,
    founded_year: '2014',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.8349939, longitude: 77.6948307, is_hq: true },
    ],
    careerUrl: 'https://www.synclovis.com/career',
  },
  {
    name: 'Persistent Systems',
    slug: 'persistent-systems',
    website: 'https://www.persistent.com/',
    description: 'See Beyond, Rise Above',
    industry: 'Cloud Consulting',
    employee_count: 10000,
    founded_year: '1990',
    offices: [
      { city: 'Pune', state: 'Maharashtra', latitude: 17.9763695, longitude: 75.7698398, is_hq: true },
    ],
    careerUrl: 'https://careers.persistent.com',
  },
  {
    name: 'Juego Studios',
    slug: 'juego-studios',
    website: 'https://www.juegostudio.com/',
    description: 'Top Game and App Development Company',
    industry: 'UX/UI Design',
    employee_count: 250,
    founded_year: '2013',
    offices: [
      { city: 'California', state: 'United States', latitude: 12.9051742, longitude: 77.5736133, is_hq: true },
    ],
    careerUrl: 'https://www.juegostudio.com/careers',
  },
  {
    name: 'nxuniq',
    slug: 'nxuniq',
    website: 'https://nxuniq.com/',
    description: 'nxuniq is the best digital marketing agency in Bangalore that focuses on brand aesthetics and the creation of unique digital content.',
    industry: 'Other Marketing',
    employee_count: 2,
    founded_year: '2021',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9190992, longitude: 77.5930939, is_hq: true },
    ],
    careerUrl: 'https://nxuniq.com/our-careers',
  },
  {
    name: 'MARS Web Solution',
    slug: 'mars-web-solution',
    website: 'https://www.marswebsolution.com/',
    description: 'MARS Web Solutions is a passionate, creative team dedicated to delivering exceptional web design and top-notch development services.',
    industry: 'SEO',
    employee_count: 10,
    founded_year: '2007',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9186079, longitude: 77.5934983, is_hq: true },
    ],
    careerUrl: 'https://www.marswebsolution.com/current-openings.html',
  },
  {
    name: 'HVJ & Associates',
    slug: 'hvj-associates',
    website: 'https://hvj.co.in/',
    description: 'HVJ &amp; Associates is a trusted Chartered Accountants firm in Bangalore providing expert accounting, auditing, taxation, and business advisory services',
    industry: 'Finance & Accounting Outsourcing (FAO)',
    employee_count: 50,
    founded_year: '2006',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 15.2028935, longitude: 77.9795817, is_hq: true },
    ],
    careerUrl: 'https://www.hvj.com/careers',
  },
  {
    name: 'Alp Consulting Ltd',
    slug: 'alp-consulting-ltd',
    website: 'https://alp.consulting/',
    description: 'Alp Consulting is a leading Indian HR &amp;staffing firm, offering tailored recruitment, payroll, and outsourcing solutions to global clients Since 1996',
    industry: 'IT Staff Augmentation',
    employee_count: 1000,
    founded_year: '1996',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 17.0904319, longitude: 75.5845516, is_hq: true },
    ],
    careerUrl: 'https://alp.consulting/careers',
  },
  {
    name: 'Indo-Sakura Software Japan K.K.',
    slug: 'indo-sakura-software-japan-k-k',
    website: 'https://indosakura.com/',
    description: 'AI-driven software and mobile app solutions, empowering businesses with innovation and scalable technology.',
    industry: 'IT Consulting',
    employee_count: 50,
    founded_year: '2005',
    offices: [
      { city: 'Tokyo', state: 'Japan', latitude: 12.8953527, longitude: 77.5673682, is_hq: true },
    ],
    careerUrl: 'https://www.careercross.com/en/company/detail-374754',
  },
  {
    name: 'Specbee',
    slug: 'specbee',
    website: 'https://www.specbee.com/',
    description: 'Specbee builds content management solutions on Drupal that can accelerate your business growth.',
    industry: 'Web Development',
    employee_count: 50,
    founded_year: '2016',
    offices: [
      { city: 'Atlanta', state: 'United States', latitude: 12.9037381, longitude: 77.6013116, is_hq: true },
    ],
    careerUrl: 'https://www.specbee.com/career',
  },
  {
    name: 'DigiMantra',
    slug: 'digimantra',
    website: 'https://digimantra.com/',
    description: 'DigiMantra is an AI-driven software and digital transformation company helping businesses build web, mobile, cloud, &amp; automation solutions that scale.',
    industry: 'Mobile App Development',
    employee_count: 250,
    founded_year: '2012',
    offices: [
      { city: 'Punjab', state: 'null', latitude: 26.9826556, longitude: 74.6759777, is_hq: true },
    ],
    careerUrl: 'https://careers.digimantra.com',
  },
  {
    name: 'CloudJournee',
    slug: 'cloudjournee',
    website: 'https://www.cloudjournee.com/',
    description: 'Cloud journey is best navigated together. At CloudJournee, we don&rsquo;t just provide services &mdash;we ensure goals are met for every cloud endeavor.',
    industry: 'Cloud Consulting',
    employee_count: 10,
    founded_year: '2016',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9100874, longitude: 77.6517163, is_hq: true },
    ],
    careerUrl: 'https://www.cloudjournee.com/careers',
  },
  {
    name: 'Versatile Club',
    slug: 'versatile-club',
    website: 'https://www.versatile.club/',
    description: 'Outsourcing and Offshoring Consulting',
    industry: 'SEO',
    employee_count: 10,
    founded_year: '2021',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9450207, longitude: 77.5695116, is_hq: true },
    ],
    careerUrl: 'https://www.versatile.ai/careers',
  },
  {
    name: 'Digitide Solutions Limited',
    slug: 'digitide-solutions-limited',
    website: 'https://www.digitide.com/',
    description: 'Digitide Solutions Limited is a global leader in AI-driven digital transformation, enabling enterprises to enhance operations and customer experiences',
    industry: 'Artificial Intelligence',
    employee_count: 10,
    founded_year: '2024',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 17.8399655, longitude: 76.1445445, is_hq: true },
    ],
    careerUrl: 'https://www.digitide.com/careers',
  },
  {
    name: 'Zerozilla Technologies',
    slug: 'zerozilla-technologies',
    website: 'https://zerozilla.com/',
    description: 'Zerozilla is your gateway to digital brilliance. We are the most valued addition your business will ever experience!',
    industry: 'SEO',
    employee_count: 250,
    founded_year: '2014',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9292185, longitude: 77.6052497, is_hq: true },
    ],
    careerUrl: 'https://zerozilla.com/careers',
  },
  {
    name: 'KriraAI Private Limited',
    slug: 'kriraai',
    website: 'https://kriraai.com/',
    description: 'Your trusted partner for AI services, mobile app & web development, data analytics, UI/UX design, branding, and more.',
    industry: 'Artificial Intelligence',
    employee_count: 10,
    founded_year: '2023',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2343121, longitude: 72.8712828, is_hq: true },
    ],
  },
  {
    name: 'Identixweb Limited',
    slug: 'identixweb-limited',
    website: 'https://www.identixweb.com/',
    description: 'We are Shopify experts helping over 12,000 merchants sell more and grow stronger with our apps & services since 2017.',
    industry: 'E-Commerce Development',
    employee_count: 50,
    founded_year: '2017',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2057507, longitude: 72.8448174, is_hq: true },
    ],
  },
  {
    name: 'DecodeUp Technologies',
    slug: 'decodeup-technologies',
    website: 'https://decodeup.com/',
    description: 'Crafting your remarkable online presence.',
    industry: 'Web Development',
    employee_count: 50,
    founded_year: '2012',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1888824, longitude: 72.7891221, is_hq: true },
    ],
  },
  {
    name: 'WebbyCrown Solutions',
    slug: 'webbycrown-solutions',
    website: 'https://www.webbycrown.com/',
    description: 'Your Challenge, Our Expertise: Together, We Solve.',
    industry: 'E-Commerce Development',
    employee_count: 10,
    founded_year: '2018',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2322993, longitude: 72.8369279, is_hq: true },
    ],
  },
  {
    name: 'Vrutti Technologies Private Limited',
    slug: 'vrutti-technologies-private-limited',
    website: 'https://vruttitech.com/',
    description: 'IoT and device-to-cloud software integration for Industry 4.0 — connect hardware, collect data, visualize insights, and automate.',
    industry: 'IoT Development',
    employee_count: 10,
    founded_year: '2022',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1964935, longitude: 72.8427426, is_hq: true },
    ],
  },
  {
    name: 'Solvsutra Software',
    slug: 'solvsutra-software',
    website: 'https://solvsutra.com/',
    description: 'Solvsutra offers AI software, website design, SEO & digital marketing to help businesses grow with smart, automated digital solutions.',
    industry: 'Web Development',
    employee_count: 10,
    founded_year: '2025',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2337382, longitude: 72.9131515, is_hq: true },
    ],
  },
  {
    name: 'Empiric Infotech LLP',
    slug: 'empiric-infotech-llp',
    website: 'https://empiricinfotech.com/',
    description: 'Hire vetted remote developers monthly - Empiric Infotech builds your team, your way.',
    industry: 'IT Staff Augmentation',
    employee_count: 50,
    founded_year: '2020',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1984679, longitude: 72.8378799, is_hq: true },
    ],
  },
  {
    name: 'Durvasa Infotech',
    slug: 'durvasa-infotech-2',
    website: 'https://durvasainfotech.com',
    description: 'Empowering businesses with innovative digital marketing, web development, and IT solutions that drive real growth.',
    industry: 'Web Development',
    employee_count: 10,
    founded_year: '2020',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2343121, longitude: 72.8712828, is_hq: true },
    ],
  },
  {
    name: 'Sarvaswa AI Labs',
    slug: 'sarvaswa-ai-labs',
    website: 'https://sarvaswa.ai',
    description: 'AI/ML Development, LLM and AI Agent Development.',
    industry: 'Artificial Intelligence',
    employee_count: 10,
    founded_year: '2024',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2329918, longitude: 72.8698902, is_hq: true },
    ],
  },
  {
    name: 'DL Minds',
    slug: 'dl-minds',
    website: 'https://dlminds.com',
    description: 'From Vision to Reality.',
    industry: 'Affiliate Marketing',
    employee_count: 10,
    founded_year: '2021',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2320551, longitude: 72.878352, is_hq: true },
    ],
  },
  {
    name: 'One.25 Tech & Design',
    slug: 'one-25-tech-design',
    website: 'https://one25techdesign.com/',
    description: 'Your One-Stop Solution for Graphic Design, Digital Marketing, Branding, Web & App Development, UI/UX and Printing.',
    industry: 'Graphic Design',
    employee_count: 10,
    founded_year: '2021',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2339447, longitude: 72.9130675, is_hq: true },
    ],
  },
  {
    name: 'Popway Software Pvt Ltd',
    slug: 'popway-software-pvt-ltd',
    website: 'https://www.popway.in',
    description: 'Surat-based IT firm with 15+ years of experience, offers web development, consulting, and software solutions for all needs.',
    industry: 'Custom Software Development',
    employee_count: 10,
    founded_year: '2009',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1845683, longitude: 72.8302575, is_hq: true },
    ],
  },
  {
    name: 'Techsoul Solutions',
    slug: 'techsoul-solutions',
    website: 'https://www.techsoulsolutions.com/',
    description: 'Techsoul Solutions builds scalable mobile apps, web platforms, and AI-powered products using modern technologies for startups and growing businesses.',
    industry: 'Mobile App Development',
    employee_count: 10,
    founded_year: '2023',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.235153, longitude: 72.8728245, is_hq: true },
    ],
  },
  {
    name: 'Team Unibrains',
    slug: 'team-unibrains',
    website: 'https://www.teamunibrains.com/',
    description: 'We deliver cost-effective, high-quality offshore web and mobile app development to deployment service, helping clients work efficiently.',
    industry: 'Web Development',
    employee_count: 10,
    founded_year: '2021',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2371184, longitude: 72.9093359, is_hq: true },
    ],
  },
  {
    name: 'Bitcoding Solutions',
    slug: 'bitcoding-solutions',
    website: 'https://bitcodingsolutions.com/',
    description: 'Best AI/ML & Python Development Company in Surat, India — Backend development, Web Scraping, App development, WordPress development, UI/UX Design.',
    industry: 'Artificial Intelligence',
    employee_count: 50,
    founded_year: '2020',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2316112, longitude: 72.8755536, is_hq: true },
    ],
  },
  {
    name: 'Vraj Technologies',
    slug: 'vraj-technologies',
    website: 'https://www.vrajtechnologies.com/',
    description: 'VRAJ Technologies provides web development, SEO, digital marketing, app development, and WhatsApp API solutions to grow businesses online.',
    industry: 'E-Commerce Development',
    employee_count: 2,
    founded_year: '2016',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1831199, longitude: 72.8718342, is_hq: true },
    ],
  },
  {
    name: 'Declone Labs Pvt Ltd',
    slug: 'declone-labs-pvt-ltd',
    website: 'https://declone.io/',
    description: 'Declone Labs is a React, Next.js & AI development company building scalable, high-performance digital products for global businesses.',
    industry: 'Web Development',
    employee_count: 10,
    founded_year: '2018',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1481451, longitude: 72.7602682, is_hq: true },
    ],
  },
  {
    name: 'Flexion Infotech Pvt Ltd',
    slug: 'flexion-infotech-pvt-ltd',
    website: 'https://flexioninfotech.com/',
    description: 'Flexion Infotech Pvt. Ltd. is a fast-growing software development and technology consulting agency headquartered at Surat, Gujarat, India.',
    industry: 'Mobile App Development',
    employee_count: 10,
    founded_year: '2021',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.238577, longitude: 72.870993, is_hq: true },
    ],
  },
  {
    name: 'ExeLance IT',
    slug: 'exelance-it',
    website: 'https://exelanceit.in/',
    description: 'Experts for your Innovations.',
    industry: 'Artificial Intelligence',
    employee_count: 50,
    founded_year: '2019',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.209118, longitude: 72.8506599, is_hq: true },
    ],
  },
  {
    name: 'Scaleteam Technologies Pvt.Ltd',
    slug: 'scaleteam-technologies-pvt-ltd',
    website: 'https://www.scale-team.com/',
    description: 'We are IT consultant and develop customized business software applications using top notch technologies. We Help Startups, Collaborate to Innovate.',
    industry: 'Mobile App Development',
    employee_count: 50,
    founded_year: '2016',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2362265, longitude: 72.8618014, is_hq: true },
    ],
  },
  {
    name: 'EbizzInfotech',
    slug: 'ebizzinfotech',
    website: 'https://www.ebizzinfotech.com/',
    description: 'If you can dream it, we can build it. Intelligent apps require brilliant design and intuitive product strategy.',
    industry: 'Mobile App Development',
    employee_count: 50,
    founded_year: '2012',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1948008, longitude: 72.8102247, is_hq: true },
    ],
  },
  {
    name: 'M-Square Technologies',
    slug: 'm-square-technologies',
    website: 'https://msquaretec.com/',
    description: 'With seven years of experience in web development and design, we have solidified our reputation as a trusted leader in our local market.',
    industry: 'Web Development',
    employee_count: 2,
    founded_year: '2017',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2114115, longitude: 72.8595689, is_hq: true },
    ],
  },
  {
    name: 'Shunyavkash',
    slug: 'shunyavkash',
    website: 'https://www.shunyavkash.com',
    description: 'Building Tomorrow\'s Digital Solutions, Today!',
    industry: 'Custom Software Development',
    employee_count: 10,
    founded_year: '2023',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2380155, longitude: 72.8879355, is_hq: true },
    ],
  },
  {
    name: 'RecurPost',
    slug: 'recurpost-social-media-scheduler-with-repeating-schedules',
    website: 'https://recurpost.com/',
    description: 'One Click, Share All Social Media Scheduler.',
    industry: 'Social Media Marketing',
    employee_count: 10,
    founded_year: '2015',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 33.9765053, longitude: -83.7434366, is_hq: true },
    ],
  },
  {
    name: 'DigiEn InfoSoft LLP',
    slug: 'digien-infosoft-llp',
    website: 'https://www.digien.in/',
    description: 'A tech company working on digitalization of enterprises.',
    industry: 'Custom Software Development',
    employee_count: 2,
    founded_year: '2017',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1828697, longitude: 72.827996, is_hq: true },
    ],
  },
  {
    name: 'MonkDA',
    slug: 'monkda',
    website: 'https://monkda.com/',
    description: 'Empowering Startups and Businesses to Grow and innovate with Technological Expertise.',
    industry: 'Mobile App Development',
    employee_count: 10,
    founded_year: '2018',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1507012, longitude: 72.7758668, is_hq: true },
    ],
  },
  {
    name: 'BRIGHTEN SOLUTIONS PVT LTD',
    slug: 'brighten-solutions-pvt-ltd',
    website: 'https://brightensolutions.com/',
    description: 'Custom Software & Websites That Scale with You from Surat, Gujarat.',
    industry: 'Custom Software Development',
    employee_count: 10,
    founded_year: '2016',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1410894, longitude: 72.7827906, is_hq: true },
    ],
  },
  {
    name: 'U & I Resources Pvt. Ltd',
    slug: 'u-i-resources-pvt-ltd',
    website: 'https://uandibrandsolutions.com/',
    description: 'U & I Resources Pvt. Ltd is one stop solution provider for your advertising, branding, marketing, events, exhibition & MICE needs, based in Surat.',
    industry: 'Advertising',
    employee_count: 10,
    founded_year: '2003',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1955148, longitude: 72.792691, is_hq: true },
    ],
  },
  {
    name: 'Limpid Systems',
    slug: 'limpid-systems',
    website: 'https://www.limpidsystems.com/',
    description: 'A software development company having expertise in web, app, custom software development, ecommerce, AI automation, and Chrome extension development.',
    industry: 'Web Development',
    employee_count: 10,
    founded_year: '2019',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.246646, longitude: 72.8902222, is_hq: true },
    ],
  },
  {
    name: 'VBS Global',
    slug: 'vbs-global',
    website: 'https://vbsglobal.co/',
    description: 'VBS Global offers outsourced bookkeeping, payroll, tax processing, and virtual CFO services for businesses in USA, UK & Australia.',
    industry: 'Finance & Accounting Outsourcing',
    employee_count: 50,
    founded_year: '2016',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2281405, longitude: 72.865786, is_hq: true },
    ],
  },
  {
    name: 'SEO Professionals',
    slug: 'seo-professionals',
    website: 'https://seoprofessionals.in/',
    description: 'Result Oriented Digital Marketing Agency.',
    industry: 'SEO',
    employee_count: 10,
    founded_year: '2008',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 40.266869, longitude: -47.8023207, is_hq: true },
    ],
  },
  {
    name: 'DashStack',
    slug: 'dashstack-infotech-ai-powered-cross-platform-full-stack-app-development',
    website: 'https://www.dashstack.tech/',
    description: 'We build scalable Flutter apps with AI, IoT, and cloud integrations to deliver high-performance cross-platform solutions.',
    industry: 'Mobile App Development',
    employee_count: 2,
    founded_year: '2022',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2302433, longitude: 72.8058015, is_hq: true },
    ],
  },
  {
    name: 'ADPenguin',
    slug: 'adpenguin',
    website: 'https://adpenguin.in/',
    description: 'AdPenguin is a digital marketing agency in Surat specializing in SEO, social media, and ads to boost brand visibility and drive business growth.',
    industry: 'SEO',
    employee_count: 2,
    founded_year: '2024',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1812291, longitude: 72.8285609, is_hq: true },
    ],
  },
  {
    name: 'Codeline Infotech LLP',
    slug: 'codeline-infotech-llp',
    website: 'https://www.codelineinfotech.com/',
    description: 'Innovative solutions for tomorrow\'s technology.',
    industry: 'Mobile App Development',
    employee_count: 10,
    founded_year: '2018',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2136852, longitude: 72.8851702, is_hq: true },
    ],
  },
  {
    name: 'Verloop Web',
    slug: 'verloop-web',
    website: 'https://verloopweb.com',
    description: 'Verloop Web - Web Development Company | SEO Services | Digital Marketing.',
    industry: 'Web Development',
    employee_count: 10,
    founded_year: '2013',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1506963, longitude: 72.773031, is_hq: true },
    ],
  },
  {
    name: 'Astha Technology Solutions Private Limited',
    slug: 'astha-technology-solutions-private-limited',
    website: 'https://asthatechnology.com',
    description: 'Astha Technology Solutions Pvt. Ltd. provides professional management with 13+ years of experience in Internet Marketing.',
    industry: 'Pay Per Click',
    employee_count: 10,
    founded_year: '2008',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2253468, longitude: 72.817052, is_hq: true },
    ],
  },
  {
    name: 'Qbits9',
    slug: 'qbits9',
    website: 'https://qbits9.com',
    description: 'Leading Technology Solutions.',
    industry: 'E-Commerce Development',
    employee_count: 10,
    founded_year: '2024',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2249103, longitude: 72.8070076, is_hq: true },
    ],
  },
  {
    name: 'SetBlue',
    slug: 'setblue',
    website: 'https://www.setblue.com/',
    description: 'Setting Brands Globally.',
    industry: 'E-Commerce Development',
    employee_count: 10,
    founded_year: '2004',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1843624, longitude: 72.8338928, is_hq: true },
    ],
  },
  {
    name: 'Codeyes Infotech',
    slug: 'codeyes-infotech',
    website: 'https://codeyesinfotech.com/',
    description: 'Codeyes offers top-notch software, mobile apps, website development, and CRM solutions to meet client needs.',
    industry: 'E-Commerce Development',
    employee_count: 10,
    founded_year: '2018',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2393062, longitude: 72.911715, is_hq: true },
    ],
  },
  {
    name: 'Meritorious Global',
    slug: 'meritorious-global',
    website: 'https://meritorious.global',
    description: '8+ Years Experience — with years of experience and a team of highly skilled professionals.',
    industry: 'Mobile App Development',
    employee_count: 10,
    founded_year: '2016',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1894981, longitude: 72.8137448, is_hq: true },
    ],
  },
  {
    name: 'Sevlex Cybersecurity',
    slug: 'sevlex-cybersecurity',
    website: 'http://www.sevlex.com',
    description: 'Sevlex Cybersecurity has simplified security by creating 3 models for small grade business to enterprise grade, making it less complicated for SMBs.',
    industry: 'Cybersecurity',
    employee_count: 2,
    founded_year: '2025',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1955592, longitude: 72.8279709, is_hq: true },
    ],
  },
  {
    name: 'Tech Innovators',
    slug: 'tech-innovators-2',
    website: 'https://techinnovators.co.in',
    description: 'We are Innovators — One of the most Versatile Team on Planet. Technology In Our Expertise.',
    industry: 'Custom Software Development',
    employee_count: 10,
    founded_year: '2019',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1870034, longitude: 72.7858663, is_hq: true },
    ],
  },
  {
    name: 'Tracely Tag',
    slug: 'tracely-tag',
    website: 'https://www.tracelytag.com/',
    description: 'TracelyTag is a secure traceability and brand protection platform combining SaaS, IoT, and smart tagging to protect your supply chain.',
    industry: 'Web Development',
    employee_count: 10,
    founded_year: '2025',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1490384, longitude: 72.7758406, is_hq: true },
    ],
  },
  {
    name: 'SEODigitalBoost',
    slug: 'seodigitalboost',
    website: 'https://seodigitalboost.com/',
    description: 'SEODigitalBoost is a Digital Marketing Agency combining AI and data science to deliver faster rankings, higher organic traffic & real business growth.',
    industry: 'Advertising',
    employee_count: 2,
    founded_year: '2021',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1851435, longitude: 72.7838509, is_hq: true },
    ],
  },
  {
    name: 'Triveni Global Software Services LLP',
    slug: 'triveni-global-software-services-llp',
    website: 'https://triveniglobalsoft.com/',
    description: 'Creating a culture of Dedication, Passion & Goals.',
    industry: 'Web Development',
    employee_count: 50,
    founded_year: '2013',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.183242, longitude: 72.7836252, is_hq: true },
    ],
  },
  {
    name: 'Fortune Analytica',
    slug: 'fortune-analytica',
    website: 'https://fortuneanalytica.com/',
    description: '360-degree digital marketing agency in India.',
    industry: 'B2B Lead Generation',
    employee_count: 10,
    founded_year: '2020',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1474821, longitude: 72.7687505, is_hq: true },
    ],
  },
  {
    name: 'santhyaseo',
    slug: 'santhyaseo',
    website: 'https://www.santhyainfotech.com/',
    description: 'Santhya Infotech offers SEO, ads, and social media marketing solutions to help businesses grow online with measurable results and lasting impact.',
    industry: 'SEO',
    employee_count: 2,
    founded_year: '2024',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1765481, longitude: 72.8186837, is_hq: true },
    ],
  },
  {
    name: 'Cinesta - Video Production Company',
    slug: 'cinesta-video-production-company',
    website: 'https://cinesta.in/',
    description: 'Cinesta Video Production creates high-quality commercials and advertisements.',
    industry: 'Video Production',
    employee_count: 10,
    founded_year: '2017',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1749662, longitude: 72.7816278, is_hq: true },
    ],
  },







  // ===== VERIFIED GREENHOUSE BOARDS =====
  {
    name: 'Postman',
    slug: 'postman',
    website: 'https://postman.com',
    description: 'API platform for building and using APIs. Used by millions of developers worldwide for testing, documenting, and sharing APIs.',
    industry: 'Developer Tools',
    ats_platform: 'greenhouse',
    ats_identifier: 'postman',
    employee_count: 700,
    founded_year: '2014',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', address: 'Koramangala, Bangalore', latitude: 12.9279, longitude: 77.6271, is_hq: true },
    ],
  },
  {
    name: 'Razorpay',
    slug: 'razorpay',
    website: 'https://razorpay.com',
    description: 'Full-stack financial solutions company. Provides payment gateway, business banking, payroll and corporate credit card services.',
    industry: 'Fintech',
    ats_platform: 'greenhouse',
    ats_identifier: 'razorpaysoftwareprivatelimited',
    employee_count: 3000,
    founded_year: '2014',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', address: 'SJR Cyber, Hosur Road, Bangalore', latitude: 12.9170, longitude: 77.6230, is_hq: true },
    ],
  },
  {
    name: 'InMobi',
    slug: 'inmobi',
    website: 'https://inmobi.com',
    description: 'Global provider of enterprise platforms for marketers. Powers intelligent, mobile-first experiences for enterprises.',
    industry: 'AdTech',
    ats_platform: 'greenhouse',
    ats_identifier: 'inmobi',
    employee_count: 1500,
    founded_year: '2007',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', address: 'Embassy Tech Village, Outer Ring Road', latitude: 12.9352, longitude: 77.6245, is_hq: true },
    ],
  },
  {
    name: 'Groww',
    slug: 'groww',
    website: 'https://groww.in',
    description: 'Investment platform making investing simple. Offers stocks, mutual funds, fixed deposits, and US equities.',
    industry: 'Fintech',
    ats_platform: 'greenhouse',
    ats_identifier: 'groww',
    employee_count: 1000,
    founded_year: '2016',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', address: 'Koramangala 1st Block, Bangalore', latitude: 12.9340, longitude: 77.6260, is_hq: true },
    ],
  },
  {
    name: 'PhonePe',
    slug: 'phonepe',
    website: 'https://phonepe.com',
    description: 'India\'s leading digital payments platform. Enables mobile payments, insurance, investments and lending.',
    industry: 'Fintech',
    ats_platform: 'greenhouse',
    ats_identifier: 'phonepe',
    employee_count: 6000,
    founded_year: '2015',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', address: 'Salarpuria Softzone, Bellandur', latitude: 12.9250, longitude: 77.6760, is_hq: true },
    ],
  },
  {
    name: 'Stripe',
    slug: 'stripe',
    website: 'https://stripe.com',
    description: 'Financial infrastructure platform. Millions of companies use Stripe to accept payments and grow revenue.',
    industry: 'Fintech',
    ats_platform: 'greenhouse',
    ats_identifier: 'stripe',
    employee_count: 8000,
    founded_year: '2010',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', address: 'Prestige Tech Park, Marathahalli', latitude: 12.9563, longitude: 77.6970, is_hq: false },
    ],
  },

  // ===== COMPANIES WITH KNOWN CAREER PAGES =====
  {
    name: 'Flipkart',
    slug: 'flipkart',
    website: 'https://flipkart.com',
    career_url: 'https://www.flipkartcareers.com/#!/joblist',
    description: 'India\'s leading e-commerce marketplace. Offers millions of products across electronics, fashion, home, and more.',
    industry: 'E-commerce',
    ats_platform: 'career_page',
    ats_identifier: null,
    employee_count: 35000,
    founded_year: '2007',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', address: 'Embassy Tech Village, Outer Ring Road', latitude: 12.9352, longitude: 77.6245, is_hq: true },
    ],
  },
  {
    name: 'Swiggy',
    slug: 'swiggy',
    website: 'https://swiggy.com',
    career_url: 'https://careers.swiggy.com',
    description: 'Food delivery and quick commerce platform. Delivers food, groceries, and essentials across Indian cities.',
    industry: 'Food Tech',
    ats_platform: 'career_page',
    ats_identifier: null,
    employee_count: 5000,
    founded_year: '2014',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', address: 'Helios Business Park, Kadabeesanahalli', latitude: 12.9380, longitude: 77.6920, is_hq: true },
    ],
  },
  {
    name: 'Zomato',
    slug: 'zomato',
    website: 'https://zomato.com',
    career_url: 'https://www.zomato.com/careers',
    description: 'Restaurant discovery, food delivery and dining platform. Also operates Blinkit for quick commerce.',
    industry: 'Food Tech',
    ats_platform: 'career_page',
    ats_identifier: null,
    employee_count: 4000,
    founded_year: '2008',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', address: 'Indiranagar, Bangalore', latitude: 12.9784, longitude: 77.6408, is_hq: false },
    ],
  },
  {
    name: 'CRED',
    slug: 'cred',
    website: 'https://cred.club',
    career_url: 'https://careers.cred.club',
    description: 'Fintech platform rewarding credit card bill payments. Offers exclusive rewards and a members-only marketplace.',
    industry: 'Fintech',
    ats_platform: 'career_page',
    ats_identifier: null,
    employee_count: 800,
    founded_year: '2018',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', address: 'HSR Layout, Bangalore', latitude: 12.9116, longitude: 77.6474, is_hq: true },
    ],
  },
  {
    name: 'Freshworks',
    slug: 'freshworks',
    website: 'https://freshworks.com',
    career_url: 'https://www.freshworks.com/company/careers',
    description: 'Cloud-based business software. Makes it fast for businesses to delight their customers and employees.',
    industry: 'SaaS',
    ats_platform: 'career_page',
    ats_identifier: null,
    employee_count: 5500,
    founded_year: '2010',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', address: 'Prestige Loka, Brunton Road', latitude: 12.9700, longitude: 77.6090, is_hq: false },
    ],
  },
  {
    name: 'Meesho',
    slug: 'meesho',
    website: 'https://meesho.com',
    career_url: 'https://careers.meesho.com',
    description: 'Social commerce platform enabling millions of small businesses to sell products online.',
    industry: 'E-commerce',
    ats_platform: 'career_page',
    ats_identifier: null,
    employee_count: 2000,
    founded_year: '2015',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', address: 'Helios Business Park, Bangalore', latitude: 12.9365, longitude: 77.6900, is_hq: true },
    ],
  },
  {
    name: 'Zerodha',
    slug: 'zerodha',
    website: 'https://zerodha.com',
    career_url: 'https://zerodha.com/careers',
    description: 'India\'s largest stock broker. Pioneered discount broking with the Kite trading platform.',
    industry: 'Fintech',
    ats_platform: 'career_page',
    ats_identifier: null,
    employee_count: 1200,
    founded_year: '2010',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', address: '#153/154, 4th Cross, J.P Nagar', latitude: 12.9070, longitude: 77.5856, is_hq: true },
    ],
  },

  // ===== COMPANIES FOR DISCOVERY (website only) =====
  {
    name: 'Zoho',
    slug: 'zoho',
    website: 'https://zoho.com',
    description: 'Suite of 55+ business apps. Serves 100M+ users globally.',
    industry: 'SaaS',
    ats_platform: null,
    ats_identifier: null,
    employee_count: 15000,
    founded_year: '1996',
    offices: [
      { city: 'Surat', state: 'Gujarat', address: 'Vesu, Surat', latitude: 21.1553, longitude: 72.7732, is_hq: false },
    ],
  },
  {
    name: 'TCS',
    slug: 'tcs',
    website: 'https://tcs.com',
    career_url: 'https://ibegin.tcs.com/iBegin/jobs/search',
    description: 'India\'s largest IT services company offering consulting, technology, and digital transformation.',
    industry: 'IT Services',
    ats_platform: 'career_page',
    ats_identifier: null,
    employee_count: 614000,
    founded_year: '1968',
    offices: [
      { city: 'Surat', state: 'Gujarat', address: 'Hazira Road, Surat', latitude: 21.1330, longitude: 72.7730, is_hq: false },
      { city: 'Bangalore', state: 'Karnataka', address: 'Whitefield, Bangalore', latitude: 12.9698, longitude: 77.7499, is_hq: false },
    ],
  },
  {
    name: 'Infosys',
    slug: 'infosys',
    website: 'https://infosys.com',
    career_url: 'https://www.infosys.com/careers.html',
    description: 'Global leader in next-generation digital services and consulting.',
    industry: 'IT Services',
    ats_platform: 'career_page',
    ats_identifier: null,
    employee_count: 340000,
    founded_year: '1981',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', address: 'Electronics City, Bangalore', latitude: 12.8458, longitude: 77.6618, is_hq: true },
    ],
  },
  {
    name: 'Wipro',
    slug: 'wipro',
    website: 'https://wipro.com',
    career_url: 'https://careers.wipro.com/careers-pages/jobs',
    description: 'Technology services and consulting company focused on digital solutions.',
    industry: 'IT Services',
    ats_platform: 'career_page',
    ats_identifier: null,
    employee_count: 250000,
    founded_year: '1945',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', address: 'Sarjapur Road, Bangalore', latitude: 12.9101, longitude: 77.6831, is_hq: true },
      { city: 'Surat', state: 'Gujarat', address: 'Vesu, Surat', latitude: 21.1565, longitude: 72.7720, is_hq: false },
    ],
  },
  {
    name: 'Tally Solutions',
    slug: 'tally-solutions',
    website: 'https://tallysolutions.com',
    career_url: 'https://tallysolutions.com/careers',
    description: 'Pioneer in business software. Tally ERP is used by millions for accounting and compliance.',
    industry: 'Enterprise Software',
    ats_platform: 'career_page',
    ats_identifier: null,
    employee_count: 2000,
    founded_year: '1986',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', address: 'Bommanahalli, Bangalore', latitude: 12.9013, longitude: 77.6182, is_hq: true },
    ],
  },
  {
    name: 'Lenskart',
    slug: 'lenskart',
    website: 'https://lenskart.com',
    career_url: 'https://www.lenskart.com/careers',
    description: 'India\'s largest omnichannel eyewear retailer with 3D try-on technology.',
    industry: 'Retail',
    ats_platform: 'career_page',
    ats_identifier: null,
    employee_count: 10000,
    founded_year: '2010',
    offices: [
      { city: 'Surat', state: 'Gujarat', address: 'Vesu Road, Surat', latitude: 21.1589, longitude: 72.7674, is_hq: false },
      { city: 'Bangalore', state: 'Karnataka', address: 'HSR Layout, Bangalore', latitude: 12.9121, longitude: 77.6446, is_hq: false },
    ],
  },
  {
    name: 'Adani Digital Labs',
    slug: 'adani-digital',
    website: 'https://adani.com',
    description: 'Technology arm of Adani Group building digital products for airports and logistics.',
    industry: 'Conglomerate Tech',
    ats_platform: null,
    ats_identifier: null,
    employee_count: 1500,
    founded_year: '2019',
    offices: [
      { city: 'Surat', state: 'Gujarat', address: 'Adani House, Navrangpura', latitude: 21.1950, longitude: 72.8240, is_hq: false },
    ],
  },
  {
    name: 'L&T Technology Services',
    slug: 'ltts',
    website: 'https://ltts.com',
    career_url: 'https://www.ltts.com/careers',
    description: 'Global engineering R&D services company.',
    industry: 'Engineering Services',
    ats_platform: 'career_page',
    ats_identifier: null,
    employee_count: 23000,
    founded_year: '2012',
    offices: [
      { city: 'Surat', state: 'Gujarat', address: 'Hazira Industrial Area', latitude: 21.1012, longitude: 72.6492, is_hq: false },
      { city: 'Bangalore', state: 'Karnataka', address: 'Whitefield, Bangalore', latitude: 12.9715, longitude: 77.7500, is_hq: false },
    ],
  },
  {
    name: 'Ola',
    slug: 'ola',
    website: 'https://olacabs.com',
    career_url: 'https://www.olacabs.com/careers',
    description: 'Ride-hailing platform. Also building Ola Electric for sustainable transportation.',
    industry: 'Mobility',
    ats_platform: 'career_page',
    ats_identifier: null,
    employee_count: 8000,
    founded_year: '2010',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', address: 'Koramangala, Bangalore', latitude: 12.9352, longitude: 77.6141, is_hq: true },
    ],
  },
  {
    name: 'Navi Technologies',
    slug: 'navi',
    website: 'https://navi.com',
    description: 'Fintech company offering personal loans, home loans, insurance and mutual funds.',
    industry: 'Fintech',
    ats_platform: null,
    ats_identifier: null,
    employee_count: 700,
    founded_year: '2018',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', address: 'Bellandur, Bangalore', latitude: 12.9250, longitude: 77.6745, is_hq: true },
    ],
  },
  {
    name: 'ShareChat',
    slug: 'sharechat',
    website: 'https://sharechat.com',
    career_url: 'https://sharechat.com/careers',
    description: 'India\'s largest homegrown social media platform. Also operates Moj.',
    industry: 'Social Media',
    ats_platform: 'career_page',
    ats_identifier: null,
    employee_count: 2500,
    founded_year: '2015',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', address: 'Koramangala 5th Block', latitude: 12.9340, longitude: 77.6170, is_hq: true },
    ],
  },
  {
    name: 'Nykaa',
    slug: 'nykaa',
    website: 'https://nykaa.com',
    career_url: 'https://careers.nykaa.com',
    description: 'Leading beauty and fashion e-commerce platform in India.',
    industry: 'E-commerce',
    ats_platform: 'career_page',
    ats_identifier: null,
    employee_count: 3500,
    founded_year: '2012',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', address: 'Indiranagar, Bangalore', latitude: 12.9780, longitude: 77.6410, is_hq: false },
    ],
  },
  {
    name: 'Capgemini',
    slug: 'capgemini',
    website: 'https://capgemini.com',
    career_url: 'https://www.capgemini.com/in-en/careers/job-search/',
    description: 'Global leader in consulting, technology services and digital transformation.',
    industry: 'IT Services',
    ats_platform: 'career_page',
    ats_identifier: null,
    employee_count: 360000,
    founded_year: '1967',
    offices: [
      { city: 'Surat', state: 'Gujarat', address: 'Vesu, Surat', latitude: 21.1545, longitude: 72.7740, is_hq: false },
      { city: 'Bangalore', state: 'Karnataka', address: 'Manyata Tech Park', latitude: 13.0477, longitude: 77.6218, is_hq: false },
    ],
  },
];
