const companies = [
  {
    name: 'Navaris Digital Pvt Ltd',
    slug: 'navaris-digital-pvt-ltd',
    website: 'https://navarisdigital.com/',
    description: 'A passionate team of innovators dedicated to transforming your digital vision into reality.',
    industry: 'Web Design',
    employee_count: 10,
    founded_year: '2016',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 13.1278929, longitude: 80.2079354, is_hq: true },
    ],
  },
  {
    name: 'Identixweb Limited',
    slug: 'identixweb-limited',
    website: 'https://www.identixweb.com/',
    description: 'We are Shopify experts helping over 12,000 merchants sell more and grow stronger with our apps & services since 2017.',
    industry: 'E-Commerce Development',
    employee_count: 50,
    founded_year: '2017',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2057507, longitude: 72.8448174, is_hq: true },
    ],
  },
  {
    name: 'Fortunesoft IT Innovations',
    slug: 'fortunesoft-it-innovations',
    website: 'https://www.fortunesoftit.com',
    description: 'Industry-Specific, Ready To Deploy Software Solutions That Drive Results',
    industry: 'Web Design',
    employee_count: 50,
    founded_year: '2009',
    offices: [
      { city: 'Nashville', state: 'United States', latitude: 12.9342151, longitude: 77.61838, is_hq: true },
    ],
  },
  {
    name: 'GeoPITS Global Pvt Ltd',
    slug: 'geopits-global-pvt-ltd',
    website: 'https://www.geopits.com/',
    description: 'Remote DBA and database solutions provider specialized in performance optimization and cloud database management across RDS, PostgreSQL, MySQL, MSSQL.',
    industry: 'Enterprise App Modernization',
    employee_count: 50,
    founded_year: '2017',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 13.0250526, longitude: 77.6590585, is_hq: true },
    ],
  },
  {
    name: 'KODA Integrated Marketing Services',
    slug: 'koda-integrated-marketing-services',
    website: 'https://koda.co.in/',
    description: 'Elevate Your Digital Presence with Koda a End to End Digital Marketing Agency',
    industry: 'Content Marketing',
    employee_count: 10,
    founded_year: '2019',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.905073, longitude: 77.6509956, is_hq: true },
    ],
  },
  {
    name: 'Conchakra Technologies Pvt Ltd',
    slug: 'conchakra-technologies-pvt-ltd',
    website: 'https://www.conchakra.com',
    description: 'AI-powered software solutions for every industry',
    industry: 'Cloud Consulting',
    employee_count: 2,
    founded_year: '2025',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 21.1910656, longitude: 72.8399872, is_hq: true },
    ],
  },
  {
    name: 'WebDigiSoft',
    slug: 'webddigisoft',
    website: 'https://www.webdigisoft.com',
    description: 'WebDigiSoft is a web design and digital marketing agency offering SEO, WordPress, eCommerce, and custom website solutions.',
    industry: 'Web Development',
    employee_count: 2,
    founded_year: '2017',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 40.266869, longitude: -179.3878585, is_hq: true },
    ],
  },
  {
    name: 'Dream Websters Infotech Private Limited',
    slug: 'dream-websters-infotech-private-limited',
    website: 'https://www.dreamwebsters.com',
    description: 'Your Dreams, Our Priority',
    industry: 'Web Development',
    employee_count: 2,
    founded_year: '2016',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 28.5332661, longitude: 77.2154769, is_hq: true },
    ],
  },
  {
    name: 'Monaqo',
    slug: 'monaqo',
    website: 'https://monaqo.in/',
    description: 'Monaqo – B2B, App, & D2C E-commerce Growth Marketing Agency in Bangalore',
    industry: 'Mobile & App Marketing',
    employee_count: 10,
    founded_year: '2017',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9783802, longitude: 77.6365823, is_hq: true },
    ],
  },
  {
    name: 'SeekNEO',
    slug: 'seekneo',
    website: 'https://www.seekneo.com',
    description: 'Seekneo is a Bangalore based tech company building scalable Websites mobile app, UI/UX, and digital marketing solutions across India &amp; global markets.',
    industry: 'Web Development',
    employee_count: 50,
    founded_year: '2010',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9846709, longitude: 77.5480523, is_hq: true },
    ],
  },
  {
    name: 'Tricon Infotech Private Limited',
    slug: 'tricon-infotech-private',
    website: 'https://www.triconinfotech.com',
    description: 'Partnering with success',
    industry: 'Artificial Intelligence',
    employee_count: 250,
    founded_year: '1997',
    offices: [
      { city: 'Hoboken', state: 'United States', latitude: 12.9303524, longitude: 77.6152457, is_hq: true },
    ],
  },
  {
    name: 'Fusion Informatics Limited',
    slug: 'fusion-informatics',
    website: 'https://www.fusioninformatic.com/',
    description: 'An offshore software development company, with expertise in web, mobile app, and custom software development based out of India, UAE, and the USA.',
    industry: 'Web Development',
    employee_count: 10,
    founded_year: '2003',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 23.0356274, longitude: 72.5182749, is_hq: true },
    ],
  },
  {
    name: 'Jordies Creative Agency',
    slug: 'jordie-s-creative-agency',
    website: 'https://jordiescreativeagency.com/',
    description: 'We build brands that people understand, remember, and return to.',
    industry: 'Branding',
    employee_count: 10,
    founded_year: '2024',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9822689, longitude: 77.5483408, is_hq: true },
    ],
  },
  {
    name: 'GKN Collective',
    slug: 'gkn-collective',
    website: 'https://gkncollective.com/',
    description: 'Strategy Before Scale',
    industry: 'Artificial Intelligence',
    employee_count: 10,
    founded_year: '2024',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 21.1910656, longitude: 72.8399872, is_hq: true },
    ],
  },
  {
    name: 'Zinavo Private Limited',
    slug: 'zinavo-private-limited',
    website: 'https://www.zinavo.com/',
    description: 'Zinavo Private Limited is a professional web design, web applcaition,web development, Mobile apps and digital marketing company based in Bangalore.',
    industry: 'Email Marketing',
    employee_count: 10,
    founded_year: '2012',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 13.0144347, longitude: 77.6480663, is_hq: true },
    ],
  },
  {
    name: 'Quantronsoft IT Consulting Pvt. Ltd.',
    slug: 'quantronsoft-it-consulting-pvt-ltd',
    website: 'https://www.quantronsoft.com/',
    description: 'Quantronsoft delivers AI, software, web development &amp; data analytics with industry training, helping businesses grow through smart digital innovation',
    industry: 'Custom Software Development',
    employee_count: 50,
    founded_year: '2026',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 20.903001, longitude: 75.6335863, is_hq: true },
    ],
  },
  {
    name: 'Adze studio',
    slug: 'adze-studio',
    website: 'https://adzestudio.com/',
    description: 'Adze Studio is a Bangalore digital marketing company delivering performance-driven strategies for quality leads and brand growth.',
    industry: 'Branding',
    employee_count: 10,
    founded_year: '2015',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.978911, longitude: 77.643472, is_hq: true },
    ],
  },
  {
    name: 'Brandsaccord',
    slug: 'brandsaccord',
    website: 'https://brandsaccord.com/',
    description: 'Brands Accord delivers website development, branding, and digital marketing services to help businesses grow with smart, data-driven online strategies',
    industry: 'Mobile App Development',
    employee_count: 10,
    founded_year: '2024',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 21.1910656, longitude: 72.8399872, is_hq: true },
    ],
  },
  {
    name: 'Zillion IT Solutions',
    slug: 'zillion-it-solutions',
    website: 'https://zillionit.com/',
    description: 'We build scalable, high-performance software that helps businesses innovate faster, streamline operations, and gain a competitive edge.',
    industry: 'Custom Software Development',
    employee_count: 2,
    founded_year: '2005',
    offices: [
      { city: 'Kozhikode', state: 'null', latitude: 21.139529, longitude: 72.7691824, is_hq: true },
    ],
  },
  {
    name: 'DeepKlarity',
    slug: 'deepklarity',
    website: 'https://deepklarity.com/',
    description: 'AI Engineering Studio',
    industry: 'Progressive Web Apps',
    employee_count: 2,
    founded_year: '2018',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 21.1910656, longitude: 72.8399872, is_hq: true },
    ],
  },
  {
    name: 'Lumos Telos',
    slug: 'lumos-telos',
    website: 'https://luxtelos.work',
    description: 'Your Partner in data, business insights & MVP solutions',
    industry: 'Custom Software Development',
    employee_count: 2,
    founded_year: '2024',
    offices: [
      { city: 'Indore', state: 'null', latitude: 23.1141762, longitude: 72.5402568, is_hq: true },
    ],
  },
  {
    name: 'Adroitte',
    slug: 'adroitte',
    website: 'https://www.adroitte.com/',
    description: 'Digital Marketing & Website Development Company in Bangalore',
    industry: 'SEO',
    employee_count: 10,
    founded_year: '2010',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9381165, longitude: 77.6308618, is_hq: true },
    ],
  },
  {
    name: 'Revver Services',
    slug: 'revver-services',
    website: 'https://www.revverservices.com/',
    description: 'Revver Services helps hotels, resorts, homestays and villas to grow online with SEO, ads, websites, and smart digital marketing solutions.',
    industry: 'SEO',
    employee_count: 10,
    founded_year: '2025',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9333308, longitude: 77.5433645, is_hq: true },
    ],
  },
  {
    name: 'Ralecon',
    slug: 'ralecon',
    website: 'https://www.ralecon.com/',
    description: 'A Decade of Digital Excellence . We specialize in delivering ROI-based digital marketing solutions that have a high success rate for our clients.',
    industry: 'SEO',
    employee_count: 50,
    founded_year: '2012',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9889227, longitude: 77.7072524, is_hq: true },
    ],
  },
  {
    name: 'Incognito Worldwide',
    slug: 'incognito-worldwide',
    website: 'http://www.incognitoworldwide.com',
    description: 'Empower Your Brand Worldwide',
    industry: 'SEO',
    employee_count: 10,
    founded_year: '2015',
    offices: [
      { city: 'Wilmington', state: 'United States', latitude: 39.7317773, longitude: -75.5785216, is_hq: true },
    ],
  },
  {
    name: 'Ralecon',
    slug: 'ralecon',
    website: 'https://www.ralecon.com/',
    description: 'A Decade of Digital Excellence . We specialize in delivering ROI-based digital marketing solutions that have a high success rate for our clients.',
    industry: 'SEO',
    employee_count: 50,
    founded_year: '2012',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9889227, longitude: 77.7072524, is_hq: true },
    ],
  },
  {
    name: 'Createxp Labs',
    slug: 'createxp-labs',
    website: 'https://createxp.in/',
    description: 'CREATEXP is a design and development studio that builds websites, MVPs, and custom software for startups and enterprises across the globe.',
    industry: 'UX/UI Design',
    employee_count: 10,
    founded_year: '2023',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 21.0680074, longitude: 82.7525294, is_hq: true },
    ],
  },
  {
    name: 'Fameweb - Digital Transformation',
    slug: 'fameweb',
    website: 'https://fameweb.in',
    description: 'A young fast-growing Branding and AI-based agency serving CGI Ads, UI/UX Design, Web/App Development & SEO Services.',
    industry: 'Branding',
    employee_count: 2,
    founded_year: '2019',
    offices: [
      { city: 'Gurugram', state: 'null', latitude: 28.4018594, longitude: 77.3051047, is_hq: true },
    ],
  },
  {
    name: 'Ekfrazo Technologies',
    slug: 'ekfrazo-technologies',
    website: 'https://ekfrazo.com/',
    description: 'Our enterprise systems help businesses cut costs by 40%, reclaim 20+ hours each week through automation, and secure operations against cyber risks.',
    industry: 'Desktop App Development',
    employee_count: 50,
    founded_year: '2015',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 13.0660382, longitude: 77.5797087, is_hq: true },
    ],
  },
  {
    name: 'Innover Digital',
    slug: 'innover-digital',
    website: 'https://www.innoverdigital.com/',
    description: 'AI-first engineering solutions strategically designed to unlock business value and intelligently propel enterprises ahead',
    industry: 'IT Strategy Consulting',
    employee_count: 1000,
    founded_year: '2020',
    offices: [
      { city: 'Alpharetta', state: 'United States', latitude: 23.5312655, longitude: 2.0663535, is_hq: true },
    ],
  },
  {
    name: 'MCUBE',
    slug: 'mcube',
    website: 'https://mcube.com/mcube-ivr/',
    description: 'MCUBE delivers smart cloud telephony solutions that simplify customer communication and boost business efficiency across all touchpoints.',
    industry: 'B2B Lead Generation',
    employee_count: 250,
    founded_year: '2009',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 17.6464545, longitude: 75.2808803, is_hq: true },
    ],
  },
  {
    name: 'WEBDIGITA',
    slug: 'webdigita',
    website: 'https://www.webdigita.com/',
    description: 'Accelerating Digital Transformation',
    industry: 'E-Commerce Development',
    employee_count: 10,
    founded_year: '2012',
    offices: [
      { city: 'Chennai', state: 'Tamil Nadu', latitude: 21.1910656, longitude: 72.8399872, is_hq: true },
    ],
  },
  {
    name: 'SAS ONE PRIVATE LIMITED',
    slug: 'sas-one-private-limited',
    website: 'https://www.sasone.in/',
    description: 'Partner for Software, Apps &amp; Embedded Systems',
    industry: 'Web Development',
    employee_count: 50,
    founded_year: '2021',
    offices: [
      { city: 'Lucknow', state: 'null', latitude: 26.8062175, longitude: 80.9917463, is_hq: true },
    ],
  },
  {
    name: 'LaunchX Labs Pvt Ltd',
    slug: 'launchx-labs-pvt-ltd',
    website: 'https://launchxlabs.ai/',
    description: 'We empower startups and businesses to transform ideas into AI-driven digital products through expert software development and strategic partnerships.',
    industry: 'Artificial Intelligence',
    employee_count: 10,
    founded_year: '2023',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9307018, longitude: 77.6866865, is_hq: true },
    ],
  },
  {
    name: 'Brandemic India LLP',
    slug: 'brandemic-india-llp',
    website: 'https://brandemic.in/',
    description: 'Brandemic is a creative branding agency offering brand strategy, digital identity, &amp; marketing solutions to help businesses grow and stand out online.',
    industry: 'Web Development',
    employee_count: 10,
    founded_year: '2020',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.919636, longitude: 77.6460796, is_hq: true },
    ],
  },
  {
    name: 'Tech Exactly',
    slug: 'tech-exactly',
    website: 'https://www.techexactly.com/',
    description: 'Helping Founders Get Their Dream App',
    industry: 'Mobile App Development',
    employee_count: 10,
    founded_year: '2017',
    offices: [
      { city: 'Kolkata', state: 'West Bengal', latitude: 22.569046, longitude: 88.435784, is_hq: true },
    ],
  },
  {
    name: 'MAP Systems',
    slug: 'map-systems',
    website: 'https://mapsystemsindia.com/',
    description: 'ePub Conversion| Photo Editing| Graphics Design| 3D Graphics',
    industry: 'Web Design',
    employee_count: 50,
    founded_year: '1993',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9406988, longitude: 77.5797078, is_hq: true },
    ],
  },
  {
    name: 'Mydbops',
    slug: 'mydbops',
    website: 'https://www.mydbops.com/',
    description: 'Mydbops offers expert database consulting, management, and support services tailored for PostgreSQL and MySQL environments.',
    industry: 'IT Managed',
    employee_count: 50,
    founded_year: '2015',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9659434, longitude: 77.6036997, is_hq: true },
    ],
  },
  {
    name: 'Jootoor Designs',
    slug: 'jootoor-designs',
    website: 'http://www.jootoor.com',
    description: 'We design your imagination',
    industry: 'SEO',
    employee_count: 2,
    founded_year: '2010',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.965007, longitude: 77.6339478, is_hq: true },
    ],
  },
  {
    name: 'Frenxt AI Consultancy',
    slug: 'frenxt-ai-consultancy',
    website: 'https://www.frenxt.com/',
    description: 'Building custom AI solutions, LLM integrations, and modern web applications for startups and growing businesses',
    industry: 'Artificial Intelligence',
    employee_count: 2,
    founded_year: '2025',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 21.2038611, longitude: 72.8462762, is_hq: true },
    ],
  },
  {
    name: 'Zethic Technologies',
    slug: 'zethic-technologies',
    website: 'http://zethic.com',
    description: 'Creative Tech Studio',
    industry: 'Custom Software Development',
    employee_count: 2,
    founded_year: '2020',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.930247, longitude: 77.6232273, is_hq: true },
    ],
  },
  {
    name: 'Blute Technologies Pvt Ltd',
    slug: 'blute-technologies-pvt-ltd',
    website: 'https://www.blute.co.in/',
    description: 'Blute Technologies is a IT application development services company and outsourcing partner for clients in all industries.',
    industry: 'Web Development',
    employee_count: 10,
    founded_year: '2019',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9186984, longitude: 77.5761684, is_hq: true },
    ],
  },
  {
    name: 'Chipsy IT Services Pvt Ltd.',
    slug: 'chipsy-information-technology-services-pvt-ltd',
    website: 'https://www.chipsyservices.com/',
    description: 'Innovating Solutions, Empowering Success.',
    industry: 'Mobile App Development',
    employee_count: 10,
    founded_year: '2012',
    offices: [
      { city: 'Udupi', state: 'null', latitude: 13.3449892, longitude: 74.7512299, is_hq: true },
    ],
  },
  {
    name: 'Eeatminds',
    slug: 'eeatminds',
    website: 'https://www.eeatminds.in/',
    description: 'Leading Digital marketing freelancer in Bangalore, India',
    industry: 'Digital Marketing',
    employee_count: 10,
    founded_year: '2015',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 14.1576412, longitude: -179.7594748, is_hq: true },
    ],
  },
  {
    name: 'VinayPN Online Services Bangalore',
    slug: 'vinaypn-online-services-bangalore',
    website: 'https://vinaypn.com/',
    description: 'VinayPN.com is a top Web Design Company Bangalore offering expert website design, development, SEO, and digital marketing services in Bangalore.',
    industry: 'Web Design',
    employee_count: 2,
    founded_year: '2014',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9877769, longitude: 77.6259217, is_hq: true },
    ],
  },
  {
    name: 'Sietrix Technologies',
    slug: 'sietrix-technologies',
    website: 'https://sietrix.com/',
    description: 'Full-service tech partner delivering web &amp; mobile apps, custom software, and CRM solutions to build scalable, efficient digital systems.',
    industry: 'CRM Consulting',
    employee_count: 2,
    founded_year: '2026',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9114431, longitude: 77.6508333, is_hq: true },
    ],
  },
  {
    name: 'Loud Mob Media',
    slug: 'loud-mob-media',
    website: 'https://www.loudmob.media',
    description: 'We are a design, strategy, technology and marketing agency for the loud, the nimble and the game-changers! From small businesses to shark tank winners...',
    industry: 'Advertising',
    employee_count: 2,
    founded_year: '2017',
    offices: [
      { city: 'Pune', state: 'Maharashtra', latitude: 12.8770054, longitude: 77.6105544, is_hq: true },
    ],
  },
  {
    name: 'DerivateX',
    slug: 'derivate-x',
    website: 'https://derivatex.agency/',
    description: 'We offer LLM SEO as a service, helping SaaS brands get discovered not just on Google, but inside AI tools like ChatGPT, Perplexity, Gemini, and Claude',
    industry: 'Marketing Strategy',
    employee_count: 10,
    founded_year: '2024',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9159399, longitude: 77.6503938, is_hq: true },
    ],
  },
  {
    name: 'Hyena Information Technologies',
    slug: 'hyena-information-technologies',
    website: 'https://www.hyena.ai/',
    description: 'Hyena Information Technologies is the most trusted software development company in bangalore, India with expertise in Mobile App Development.',
    industry: 'Mobile App Development',
    employee_count: 50,
    founded_year: '1999',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 15.1748337, longitude: 78.0006644, is_hq: true },
    ],
  },
  {
    name: 'PixxelCodeLabs',
    slug: 'pixxelcodelabs',
    website: 'https://pixxelcodelabs.com',
    description: 'At PixxelCodeLabs, we are more than just a digital agency&mdash;we are your strategic partners in crafting engaging experiences, create innovative solutions',
    industry: 'Web Development',
    employee_count: 50,
    founded_year: '2024',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 40.266869, longitude: -179.3878585, is_hq: true },
    ],
  },
  {
    name: 'SEOBangalore',
    slug: 'seobangalore',
    website: 'https://www.seobangalore.in/',
    description: 'Leading SEO Company in Bangalore with 13+ years of expertise Experts in AEO, SXO, GEO, City-Based & Technical SEO.',
    industry: 'SEO',
    employee_count: 10,
    founded_year: '2017',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 9.3741102, longitude: -74.9524576, is_hq: true },
    ],
  },
  {
    name: 'doodleblue Innovations',
    slug: 'doodleblue',
    website: 'http://www.doodleblue.com/',
    description: 'Digital Strategy Consulting',
    industry: 'Mobile App Development',
    employee_count: 50,
    founded_year: '2012',
    offices: [
      { city: 'Chennai', state: 'Tamil Nadu', latitude: 12.9944032, longitude: 78.9191, is_hq: true },
    ],
  },
  {
    name: 'Synclovis Systems Pvt. Ltd.',
    slug: 'synclovis-systems',
    website: 'http://www.synclovis.com',
    description: 'Customized Mobile & Web Apps Development',
    industry: 'Mobile App Development',
    employee_count: 10,
    founded_year: '2014',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.8349939, longitude: 77.6948307, is_hq: true },
    ],
  },
  {
    name: 'Devout Growth',
    slug: 'devout-growth',
    website: 'https://www.devoutgrowth.com/',
    description: 'Devout Growth is a top digital marketing agency in India that helps businesses grow online.',
    industry: 'Digital Marketing',
    employee_count: 50,
    founded_year: '2017',
    offices: [
      { city: 'Patna', state: 'null', latitude: 25.628975, longitude: 85.1074811, is_hq: true },
    ],
  },
  {
    name: 'Persistent Systems',
    slug: 'persistent-systems',
    website: 'https://www.persistent.com/',
    description: 'See Beyond, Rise Above',
    industry: 'Cloud Consulting',
    employee_count: 10000,
    founded_year: '1990',
    offices: [
      { city: 'Pune', state: 'Maharashtra', latitude: 17.9763695, longitude: 75.7698398, is_hq: true },
    ],
  },
  {
    name: 'Arffy Technologies Private limited',
    slug: 'arffy-technologies-private-limited',
    website: 'https://www.arffy.com/',
    description: 'Arffy Technologies Private limited is a dynamic software company known for its innovative solutions and commitment to excellence in the tech industry.',
    industry: 'Artificial Intelligence',
    employee_count: 50,
    founded_year: '2022',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.8134592, longitude: 77.5779706, is_hq: true },
    ],
  },
  {
    name: 'Founders Media',
    slug: 'founders-media',
    website: 'https://foundersmedia.in/',
    description: 'Healthcare &amp; Realestate Marketing Experts',
    industry: 'Digital Marketing',
    employee_count: 2,
    founded_year: '2020',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 32.197012, longitude: 38.751559, is_hq: true },
    ],
  },
  {
    name: 'Market Kapchur',
    slug: 'market-kapchur',
    website: 'https://marketkapchur.com/',
    description: 'Market Kapchur is a digital marketing company providing SEO, Performance Marketing, &amp; Brand Development.',
    industry: 'Branding',
    employee_count: 10,
    founded_year: '2023',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 13.030076, longitude: 77.6306073, is_hq: true },
    ],
  },
  {
    name: 'ThePro3DStudio',
    slug: 'thepro3dstudio',
    website: 'https://professional3dservices.com/',
    description: '3D Design Studio',
    industry: 'Product Design',
    employee_count: 50,
    founded_year: '2017',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9407212, longitude: 77.579735, is_hq: true },
    ],
  },
  {
    name: 'AppsWise Technologies',
    slug: 'appswise-technologies',
    website: 'https://appswise.com',
    description: 'Application wise technologies implementaion!',
    industry: 'Custom Software Development',
    employee_count: 10,
    founded_year: '2016',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.8539503, longitude: 77.7710858, is_hq: true },
    ],
  },
  {
    name: 'Mathew Digital',
    slug: 'mathew-digital',
    website: 'https://mathewdigital.com/',
    description: 'Digital Marketing Agency in Bangalore | Growth Focused Performance Marketing for B2B and D2C. Lead-gen & revenue growth.',
    industry: 'Pay Per Click',
    employee_count: 10,
    founded_year: '2016',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9564031, longitude: 77.6491589, is_hq: true },
    ],
  },
  {
    name: 'First Launch - A Full Service Marketing Agency',
    slug: 'first-launch',
    website: 'https://firstlaunch.in/',
    description: 'A full-service marketing agency from Bangalore, India, providing digital marketing, visual (branding, graphic design) & website development solutions.',
    industry: 'SEO',
    employee_count: 10,
    founded_year: '2017',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 17.0751611, longitude: 75.1735476, is_hq: true },
    ],
  },
  {
    name: 'Scool360',
    slug: 'scool360',
    website: 'https://scool360.com/',
    description: 'Scool360 is a school management software designed to streamline administrative tasks, enhance communication, and optimize educational processes.',
    industry: 'Advertising',
    employee_count: 50,
    founded_year: '2019',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.890156, longitude: 77.6107392, is_hq: true },
    ],
  },
  {
    name: 'NAVAM Digital LLC',
    slug: 'navam-digital-llc',
    website: 'https://navamdigital.com/',
    description: 'Transforming tomorrow&#39;s digital landscape with innovative solutions, leveraging technology to drive growth and complete business transformations.',
    industry: 'CRM Consulting',
    employee_count: 2,
    founded_year: '2023',
    offices: [
      { city: 'Valencia, CA', state: 'United States', latitude: 21.1910656, longitude: 72.8399872, is_hq: true },
    ],
  },
  {
    name: 'Tonse Business Solutions',
    slug: 'tonse-business-solutions',
    website: 'https://tonsetech.com',
    description: 'Tonsetech is a global-first technology company enabling Indian businesses to scale smarter with tailored, industry-ready digital solutions.',
    industry: 'Artificial Intelligence',
    employee_count: 50,
    founded_year: '2014',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: -10.5050406, longitude: 48.0818417, is_hq: true },
    ],
  },
  {
    name: 'GoodWorkLabs',
    slug: 'goodworklabs',
    website: 'http://www.goodworklabs.com',
    description: 'Leading Tech & Digital Transformation Company',
    industry: 'Mobile App Development',
    employee_count: 50,
    founded_year: '2012',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.979772, longitude: 77.724389, is_hq: true },
    ],
  },
  {
    name: 'Juego Studios',
    slug: 'juego-studios',
    website: 'https://www.juegostudio.com/',
    description: 'Top Game and App Development Company',
    industry: 'UX/UI Design',
    employee_count: 250,
    founded_year: '2013',
    offices: [
      { city: 'California', state: 'United States', latitude: 12.9051742, longitude: 77.5736133, is_hq: true },
    ],
  },
  {
    name: 'TransformEdge',
    slug: 'transformedge',
    website: 'https://transformedge.com',
    description: 'End to End Cloud ERP Implementations , Integrations and AI Driven Process Automation Specialist, ERP Focused Agentic AI Consulting Solutions Provider',
    industry: 'Oracle Consultancy',
    employee_count: 50,
    founded_year: '2016',
    offices: [
      { city: 'Wilmington DE', state: 'United States', latitude: 12.9148489, longitude: 77.5865864, is_hq: true },
    ],
  },
  {
    name: 'Athena Business Solutions',
    slug: 'athena-business-solutions',
    website: 'https://athenabizsolutions.com/',
    description: 'Athena Business Solutions is a digital marketing agency that helps businesses grow through marketing, branding, and digital strategy.',
    industry: 'Web Development',
    employee_count: 10,
    founded_year: '2018',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9768142, longitude: 77.6192185, is_hq: true },
    ],
  },
  {
    name: 'Onboardnow',
    slug: 'onboardnow',
    website: 'https://www.onboardnow.ai/',
    description: 'One-stop hiring: Pre-vetted domain experts, time-zone aligned, onboarded in 48h to blend seamlessly with your team',
    industry: 'IT Staff Augmentation',
    employee_count: 50,
    founded_year: '2024',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 51.1163189, longitude: 6.8866457, is_hq: true },
    ],
  },
  {
    name: 'FusionEventz',
    slug: 'fusioneventz',
    website: 'https://fusioneventz.in',
    description: 'FusionEventz is a leading event management company based in Bangalore. Best Corporate Event Management Company in Bangalore',
    industry: 'Event Marketing & Planning',
    employee_count: 2,
    founded_year: '2014',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 13.0784499, longitude: 77.574591, is_hq: true },
    ],
  },
  {
    name: 'Shrote Technology',
    slug: 'shrote-technology',
    website: 'https://www.shrote.com',
    description: 'Shrote Technology delivers innovative web, software, and digital solutions, turning ideas into reality with the motto -- Your Vision, Our Code.',
    industry: 'Artificial Intelligence',
    employee_count: 50,
    founded_year: '2024',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 20.7723776, longitude: 77.4851212, is_hq: true },
    ],
  },
  {
    name: 'nxuniq',
    slug: 'nxuniq',
    website: 'https://nxuniq.com/',
    description: 'nxuniq is the best digital marketing agency in Bangalore that focuses on brand aesthetics and the creation of unique digital content.',
    industry: 'Other Marketing',
    employee_count: 2,
    founded_year: '2021',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9190992, longitude: 77.5930939, is_hq: true },
    ],
  },
  {
    name: 'Digital SVP',
    slug: 'digital-svp',
    website: 'https://www.digitalsvp.com/',
    description: 'Shreyas V Patil, Leading Freelance Digital Marketer In Bangalore, India with 10+ years of Expirence in SEO, SEM, SMO, SMM, Web Design/Dev.',
    industry: 'Digital Marketing',
    employee_count: 1,
    founded_year: '2020',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 21.4597912, longitude: 73.9363081, is_hq: true },
    ],
  },
  {
    name: 'MARS Web Solution',
    slug: 'mars-web-solution',
    website: 'https://www.marswebsolution.com/',
    description: 'MARS Web Solutions is a passionate, creative team dedicated to delivering exceptional web design and top-notch development services.',
    industry: 'SEO',
    employee_count: 10,
    founded_year: '2007',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9186079, longitude: 77.5934983, is_hq: true },
    ],
  },
  {
    name: 'HVJ & Associates',
    slug: 'hvj-associates',
    website: 'https://hvj.co.in/',
    description: 'HVJ &amp; Associates is a trusted Chartered Accountants firm in Bangalore providing expert accounting, auditing, taxation, and business advisory services',
    industry: 'Finance & Accounting Outsourcing (FAO)',
    employee_count: 50,
    founded_year: '2006',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 15.2028935, longitude: 77.9795817, is_hq: true },
    ],
  },
  {
    name: 'Alp Consulting Ltd',
    slug: 'alp-consulting-ltd',
    website: 'https://alp.consulting/',
    description: 'Alp Consulting is a leading Indian HR &amp;staffing firm, offering tailored recruitment, payroll, and outsourcing solutions to global clients Since 1996',
    industry: 'IT Staff Augmentation',
    employee_count: 1000,
    founded_year: '1996',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 17.0904319, longitude: 75.5845516, is_hq: true },
    ],
  },
  {
    name: 'Indo-Sakura Software Japan K.K.',
    slug: 'indo-sakura-software-japan-k-k',
    website: 'https://indosakura.com/',
    description: 'AI-driven software and mobile app solutions, empowering businesses with innovation and scalable technology.',
    industry: 'IT Consulting',
    employee_count: 50,
    founded_year: '2005',
    offices: [
      { city: 'Tokyo', state: 'Japan', latitude: 12.8953527, longitude: 77.5673682, is_hq: true },
    ],
  },
  {
    name: 'Specbee',
    slug: 'specbee',
    website: 'https://www.specbee.com/',
    description: 'Specbee builds content management solutions on Drupal that can accelerate your business growth.',
    industry: 'Web Development',
    employee_count: 50,
    founded_year: '2016',
    offices: [
      { city: 'Atlanta', state: 'United States', latitude: 12.9037381, longitude: 77.6013116, is_hq: true },
    ],
  },
  {
    name: 'Digitalpix',
    slug: 'digitalpix',
    website: 'https://digitalpix.in/',
    description: 'Digitalpix is a digital agency delivering tailored marketing, branding, and web solutions to help businesses grow and succeed online.',
    industry: 'Digital Marketing',
    employee_count: 10,
    founded_year: '2020',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 27.6406731, longitude: -5.3249988, is_hq: true },
    ],
  },
  {
    name: 'MN Service Providers',
    slug: 'mn-service-providers',
    website: 'https://www.mnserviceproviders.com/',
    description: 'We are a leading AI-driven IT services provider in India, dedicated to empowering startups, contractors, and facilities management firms.',
    industry: 'Web Development',
    employee_count: 10,
    founded_year: '2007',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.94816, longitude: 77.6234106, is_hq: true },
    ],
  },
  {
    name: 'DigiMantra',
    slug: 'digimantra',
    website: 'https://digimantra.com/',
    description: 'DigiMantra is an AI-driven software and digital transformation company helping businesses build web, mobile, cloud, &amp; automation solutions that scale.',
    industry: 'Mobile App Development',
    employee_count: 250,
    founded_year: '2012',
    offices: [
      { city: 'Punjab', state: 'null', latitude: 26.9826556, longitude: 74.6759777, is_hq: true },
    ],
  },
  {
    name: 'Confe Systems',
    slug: 'confe-systems',
    website: 'https://confemedia.com/',
    description: 'More than a software development company, we build business growth engines.',
    industry: 'Web Development',
    employee_count: 2,
    founded_year: '2024',
    offices: [
      { city: 'Denver', state: 'United States', latitude: 21.1910656, longitude: 72.8399872, is_hq: true },
    ],
  },
  {
    name: 'Spear Growth',
    slug: 'spear-growth',
    website: 'https://speargrowth.com',
    description: 'Ads & SEO for B2B SaaS Companies',
    industry: 'Advertising',
    employee_count: 10,
    founded_year: '2021',
    offices: [
      { city: 'Ghaziabad', state: 'null', latitude: 12.9103462, longitude: 77.6328089, is_hq: true },
    ],
  },
  {
    name: 'Back B solutions LLP',
    slug: 'back-b-solutions-llp',
    website: 'https://backb.ca/',
    description: 'Back B is a top website design and development company, offering custom solutions in e-commerce, WordPress, and more to drive business growth online.',
    industry: 'Web Development',
    employee_count: 10,
    founded_year: '2019',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9572098, longitude: 77.7087173, is_hq: true },
    ],
  },
  {
    name: 'CloudJournee',
    slug: 'cloudjournee',
    website: 'https://www.cloudjournee.com/',
    description: 'Cloud journey is best navigated together. At CloudJournee, we don&rsquo;t just provide services &mdash;we ensure goals are met for every cloud endeavor.',
    industry: 'Cloud Consulting',
    employee_count: 10,
    founded_year: '2016',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9100874, longitude: 77.6517163, is_hq: true },
    ],
  },
  {
    name: 'nxtwat',
    slug: 'nxtwat',
    website: 'https://nxtwat.com',
    description: 'NXTWAT, a top web design and development company in Bangalore with 8+ years of experience, offers responsive websites,',
    industry: 'Web Development',
    employee_count: 10,
    founded_year: '2022',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 13.0571893, longitude: 77.5924306, is_hq: true },
    ],
  },
  {
    name: 'Clonet Technologies Private Limited',
    slug: 'clonet-technologies-private-limited',
    website: 'https://nuclonet.com/',
    description: 'Manufacturer of Electronics weighing scale &amp; systems, Point of Sale Hardware and Software, Printer, Label Printer and POS scale, Scanner &amp; Cashdrawers',
    industry: 'Custom Software Development',
    employee_count: 50,
    founded_year: '2017',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9226038, longitude: 77.6139254, is_hq: true },
    ],
  },
  {
    name: 'NVT IT Solutions',
    slug: 'nvt-it-solutions',
    website: 'https://www.nvtitsolutions.com',
    description: 'We are a prominent software development company based in Bangalore that specialises in a wide range of digital services.',
    industry: 'SMM',
    employee_count: 10,
    founded_year: '2022',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 21.1603877, longitude: 76.4114534, is_hq: true },
    ],
  },
  {
    name: 'Versatile Club',
    slug: 'versatile-club',
    website: 'https://www.versatile.club/',
    description: 'Outsourcing and Offshoring Consulting',
    industry: 'SEO',
    employee_count: 10,
    founded_year: '2021',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9450207, longitude: 77.5695116, is_hq: true },
    ],
  },
  {
    name: 'Digitide Solutions Limited',
    slug: 'digitide-solutions-limited',
    website: 'https://www.digitide.com/',
    description: 'Digitide Solutions Limited is a global leader in AI-driven digital transformation, enabling enterprises to enhance operations and customer experiences',
    industry: 'Artificial Intelligence',
    employee_count: 10,
    founded_year: '2024',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 17.8399655, longitude: 76.1445445, is_hq: true },
    ],
  },
  {
    name: 'Zerozilla Technologies',
    slug: 'zerozilla-technologies',
    website: 'https://zerozilla.com/',
    description: 'Zerozilla is your gateway to digital brilliance. We are the most valued addition your business will ever experience!',
    industry: 'SEO',
    employee_count: 250,
    founded_year: '2014',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9292185, longitude: 77.6052497, is_hq: true },
    ],
  },
  {
    name: 'Mavenwit',
    slug: 'mavenwit',
    website: 'https://www.mavenwit.com/',
    description: 'An Award Winning Full-Time Global Advertising, Marketing & Innovational Transformation Company.',
    industry: 'Advertising',
    employee_count: 50,
    founded_year: '2020',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 21.1910656, longitude: 72.8399872, is_hq: true },
    ],
  },
  {
    name: 'DINTW',
    slug: 'dintw',
    website: 'https://www.dintw.com',
    description: 'Making Marketing Work',
    industry: 'Digital Strategy',
    employee_count: 10,
    founded_year: '2015',
    offices: [
      { city: 'Noida', state: 'null', latitude: 21.1910656, longitude: 72.8399872, is_hq: true },
    ],
  },
  {
    name: 'Vibhava Creations',
    slug: 'vibhava-creations',
    website: 'https://vibhavacreations.com',
    description: 'Vibhava Creations - Your Next-Gen Creative Destination',
    industry: 'Digital Marketing',
    employee_count: 2,
    founded_year: '2021',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 17.0918625, longitude: 75.203566, is_hq: true },
    ],
  },
  {
    name: 'GeekyAnts',
    slug: 'geekyants',
    website: 'http://geekyants.com/',
    description: 'Web and Mobile App Development Experts',
    industry: 'Web Development',
    employee_count: 50,
    founded_year: '2005',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', latitude: 12.9107216, longitude: 77.6018313, is_hq: true },
    ],
  }
];

module.exports = companies;
