"""
Client script — calls the deployed Qwen3 Agent on Modal to research
company career pages and writes results back to companiesCareerUrl.js

Usage:
    python run_career_search.py              # Research all from companies.js
    python run_career_search.py "Stripe"     # Research specific companies
    python run_career_search.py --dry-run    # Preview without calling API
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import httpx

# ─── Paths ────────────────────────────────────────────────────────────────
SCRIPT_DIR = Path(__file__).parent
COMPANIES_JS = SCRIPT_DIR / ".." / "src" / "scrapers" / "companies.js"
OUTPUT_JS = SCRIPT_DIR / ".." / "src" / "scrapers" / "companiesCareerUrl.js"

# ─── Deployed Modal endpoint URL ─────────────────────────────────────────
API_URL = "https://webdevshubhanshu--qwen3-agent-api-chat.modal.run"


def parse_companies_js(filepath: Path) -> list[dict]:
    """Parse companies.js and extract company objects."""
    text = filepath.read_text(encoding="utf-8")

    match = re.search(r"const\s+companies\s*=\s*\[(.+)\];", text, re.DOTALL)
    if not match:
        print("❌ Could not parse companies.js")
        return []

    array_body = match.group(1)

    # Remove JS comments (block comments first, then line comments outside strings)
    array_body = re.sub(r"/\*.*?\*/", "", array_body, flags=re.DOTALL)
    array_body = re.sub(r"(?<![\"':])//.*?$", "", array_body, flags=re.MULTILINE)

    # Convert JS → JSON
    array_body = re.sub(r"'", '"', array_body)
    # Convert JS `undefined` to JSON `null`
    array_body = re.sub(r'\bundefined\b', 'null', array_body)
    # Quote unquoted JS object keys (only after { , or newline to avoid breaking URLs)
    array_body = re.sub(
        r'(?<=[\{\,\n])\s*(\w+)\s*:',
        lambda m: f' "{m.group(1)}":',
        array_body,
    )
    array_body = re.sub(r",\s*([}\]])", r"\1", array_body)

    try:
        return json.loads(f"[{array_body}]")
    except json.JSONDecodeError as e:
        print(f"⚠️  JSON parse fallback (regex mode): {e}")
        names = re.findall(r"name:\s*['\"](.+?)['\"]", text)
        websites = re.findall(r"website:\s*['\"](.+?)['\"]", text)
        return [{"name": n, "website": w} for n, w in zip(names, websites)]


def format_js_value(value, indent: int = 4) -> str:
    """Convert a Python value to its JavaScript representation."""
    prefix = " " * indent
    if value is None:
        return "undefined"
    elif isinstance(value, bool):
        return "true" if value else "false"
    elif isinstance(value, (int, float)):
        return str(value)
    elif isinstance(value, str):
        escaped = value.replace("'", "\\'")
        return f"'{escaped}'"
    elif isinstance(value, dict):
        inner = ", ".join(
            f"{k}: {format_js_value(v, indent)}" for k, v in value.items()
        )
        return "{ " + inner + " }"
    elif isinstance(value, list):
        if not value:
            return "[]"
        # Check if list contains objects (dicts)
        if any(isinstance(item, dict) for item in value):
            items = []
            for item in value:
                items.append(f"{prefix}  {format_js_value(item, indent + 2)}")
            return "[\n" + ",\n".join(items) + f",\n{prefix}]"
        else:
            items = [format_js_value(item, indent) for item in value]
            return "[" + ", ".join(items) + "]"
    else:
        return f"'{value}'"


def write_results_js(results: list[dict], output_path: Path):
    """Write results as a JS module file."""
    from datetime import datetime, timezone

    lines = [
        "/**",
        " * Companies with discovered career page URLs",
        f" * Auto-generated by run_career_search.py on {datetime.now(timezone.utc).isoformat()}",
        f" * Total: {len(results)} companies",
        " */",
        "const companiesWithCareerUrls = [",
    ]

    for company in results:
        lines.append("  {")
        for key, value in company.items():
            formatted = format_js_value(value, indent=4)
            lines.append(f"    {key}: {formatted},")
        lines.append("  },")

    lines.append("];")
    lines.append("")
    lines.append("module.exports = companiesWithCareerUrls;")
    lines.append("")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"✅ Wrote {len(results)} companies to {output_path}")


def extract_career_url(response_text: str, company_website: str = "") -> str | None:
    """
    Parse the agent's JSON response to extract career_url.
    Returns None if null or if the URL looks fabricated.
    """
    json_match = re.search(r'\{[^{}]*"career_url"[^{}]*\}', response_text, re.DOTALL)
    if json_match:
        try:
            data = json.loads(json_match.group(0))
            url = data.get("career_url")
            confidence = data.get("confidence", "none")

            if not url or url == "null" or url == "None":
                return None
            if confidence == "none":
                return None

            # Reject fabricated URLs (just website + /careers)
            if company_website:
                base = company_website.rstrip("/")
                fabricated = [
                    f"{base}/careers", f"{base}/career",
                    f"{base}/jobs", f"{base}/job",
                    f"{base}/work-with-us", f"{base}/join-us",
                ]
                if url.rstrip("/") in [f.rstrip("/") for f in fabricated]:
                    if confidence != "high":
                        return None

            return url.rstrip("/.,;:")
        except json.JSONDecodeError:
            pass

    # Fallback: look for career-related URLs (not fabricated ones)
    urls = re.findall(r"https?://[^\s\)\]\},\"']+", response_text)
    career_keywords = ["career", "job", "hiring", "talent", "recruit", "apply", "openings"]
    for url in urls:
        url_lower = url.lower()
        if any(kw in url_lower for kw in career_keywords):
            if company_website:
                base = company_website.rstrip("/").lower()
                if url_lower.rstrip("/") in (f"{base}/careers", f"{base}/jobs"):
                    continue
            return url.rstrip("/.,;:")

    return None


def call_agent(query: str, system_prompt: str, timeout: float = 180.0) -> dict | None:
    """Call the deployed Modal agent via HTTP POST."""
    try:
        resp = httpx.post(
            API_URL,
            json={"query": query, "system_prompt": system_prompt},
            timeout=timeout,
        )
        resp.raise_for_status()
        return resp.json()
    except httpx.TimeoutException:
        print("   ⏳ Timed out (GPU container may still be starting)")
        return None
    except httpx.HTTPStatusError as e:
        print(f"   ❌ HTTP {e.response.status_code}: {e.response.text[:200]}")
        return None
    except Exception as e:
        print(f"   ❌ Request error: {e}")
        return None


def main():
    args = sys.argv[1:]
    dry_run = "--dry-run" in args
    args = [a for a in args if a != "--dry-run"]

    # ── Load companies ──
    if args:
        companies = [{"name": name} for name in args]
    else:
        if not COMPANIES_JS.exists():
            print(f"❌ {COMPANIES_JS} not found")
            sys.exit(1)
        companies = parse_companies_js(COMPANIES_JS)

    if not companies:
        print("❌ No companies found to research")
        sys.exit(1)

    print(f"🏢 Found {len(companies)} companies to research")
    for c in companies:
        print(f"   • {c['name']}")

    if dry_run:
        print("\n🔍 Dry run — no API calls made")
        return

    print(f"\n🔗 Endpoint: {API_URL}")
    print("   (First request may take ~2 min while GPU starts)\n")

    json_example = '{"career_url": "<url or null>", "source": "<where you found it>", "confidence": "high/low/none"}'

    system_prompt = (
        "You are a strict career page verifier. You MUST use the web_search or "
        "search_company_careers tool before answering. You are FORBIDDEN from "
        "guessing URLs. If you did not find a career page URL in the actual "
        "search results, you MUST return null for career_url. "
        "Never assume a URL exists - only report what the search results show. "
        "Respond with JSON only."
    )

    results = []
    skipped = []
    total = len(companies)

    for i, company in enumerate(companies, 1):
        name = company["name"]
        website = company.get("website", "")

        print(f"[{i}/{total}] 🔍 Researching: {name}")

        company_info = f"'{name}'"
        if website:
            company_info += f" (website: {website})"

        query = (
            "Search the web for the careers or jobs page of " + company_info + ".\n\n"
            "INSTRUCTIONS:\n"
            "1. You MUST call the search tool first. Do NOT skip searching.\n"
            "2. Look through the search results carefully for any career/jobs page URL.\n"
            "3. Only report a URL if you actually found it in the search results.\n"
            "4. Do NOT guess or fabricate a URL (e.g. do NOT just append /careers to the website).\n"
            "5. If the search results do not contain a careers page URL, say career_url is null.\n\n"
            "After searching, respond ONLY with this JSON (no other text):\n"
            + json_example
        )

        r = call_agent(query, system_prompt)

        if r is None:
            skipped.append(name)
            continue

        response = r.get("response", "")
        tool_calls = r.get("tool_calls", [])

        # If model didn't use tools, retry once with a stronger prompt
        if not tool_calls:
            print(f"   ⚠️  No tools used, retrying with stronger prompt...")
            retry_query = (
                "You MUST use the search_company_careers tool right now to search for: "
                + company_info + "\n"
                "Do NOT answer from memory. Call the tool first, then respond with JSON.\n"
                + json_example
            )
            r = call_agent(retry_query, system_prompt)

            if r is None:
                skipped.append(name)
                continue

            response = r.get("response", "")
            tool_calls = r.get("tool_calls", [])

            if not tool_calls:
                print(f"   ❌ Model still refused to search — skipping")
                skipped.append(name)
                continue

        career_url = extract_career_url(response, website)

        if career_url:
            result = {
                "name": name,
                **{k: v for k, v in company.items() if k != "name"},
                "careerUrl": career_url,
            }
            results.append(result)
            print(f"   ✅ {career_url}")
        else:
            print(f"   ❌ No career URL in search results")
            skipped.append(name)

    # ── Write results ──
    if results:
        write_results_js(results, OUTPUT_JS)
    else:
        print("\n⚠️  No results to write")

    # ── Summary ──
    print(f"\n{'=' * 50}")
    print(f"📊 Summary")
    print(f"   Total: {total}")
    print(f"   Found: {len(results)}")
    print(f"   Skipped: {len(skipped)}")
    if skipped:
        for s in skipped:
            print(f"     • {s}")


if __name__ == "__main__":
    main()
