const companies = [
  {
    name: 'KriraAI Private Limited',
    slug: 'kriraai',
    website: 'https://kriraai.com/',
    description: 'Your trusted partner for AI services, mobile app & web development, data analytics, UI/UX design, branding, and more.',
    industry: 'Artificial Intelligence',
    employee_count: 10,
    founded_year: '2023',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2343121, longitude: 72.8712828, is_hq: true },
    ],
  },
  {
    name: 'DecodeUp Technologies',
    slug: 'decodeup-technologies',
    website: 'https://decodeup.com/',
    description: 'Crafting your remarkable online presence.',
    industry: 'Web Development',
    employee_count: 50,
    founded_year: '2012',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1888824, longitude: 72.7891221, is_hq: true },
    ],
  },
  {
    name: 'WebbyCrown Solutions',
    slug: 'webbycrown-solutions',
    website: 'https://www.webbycrown.com/',
    description: 'Your Challenge, Our Expertise: Together, We Solve.',
    industry: 'E-Commerce Development',
    employee_count: 10,
    founded_year: '2018',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2322993, longitude: 72.8369279, is_hq: true },
    ],
  },
  {
    name: 'Vrutti Technologies Private Limited',
    slug: 'vrutti-technologies-private-limited',
    website: 'https://vruttitech.com/',
    description: 'IoT and device-to-cloud software integration for Industry 4.0 — connect hardware, collect data, visualize insights, and automate.',
    industry: 'IoT Development',
    employee_count: 10,
    founded_year: '2022',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1964935, longitude: 72.8427426, is_hq: true },
    ],
  },
  {
    name: 'Solvsutra Software',
    slug: 'solvsutra-software',
    website: 'https://solvsutra.com/',
    description: 'Solvsutra offers AI software, website design, SEO & digital marketing to help businesses grow with smart, automated digital solutions.',
    industry: 'Web Development',
    employee_count: 10,
    founded_year: '2025',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2337382, longitude: 72.9131515, is_hq: true },
    ],
  },
  {
    name: 'Empiric Infotech LLP',
    slug: 'empiric-infotech-llp',
    website: 'https://empiricinfotech.com/',
    description: 'Hire vetted remote developers monthly - Empiric Infotech builds your team, your way.',
    industry: 'IT Staff Augmentation',
    employee_count: 50,
    founded_year: '2020',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1984679, longitude: 72.8378799, is_hq: true },
    ],
  },
  {
    name: 'Durvasa Infotech',
    slug: 'durvasa-infotech-2',
    website: 'https://durvasainfotech.com',
    description: 'Empowering businesses with innovative digital marketing, web development, and IT solutions that drive real growth.',
    industry: 'Web Development',
    employee_count: 10,
    founded_year: '2020',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2343121, longitude: 72.8712828, is_hq: true },
    ],
  },
  {
    name: 'Sarvaswa AI Labs',
    slug: 'sarvaswa-ai-labs',
    website: 'https://sarvaswa.ai',
    description: 'AI/ML Development, LLM and AI Agent Development.',
    industry: 'Artificial Intelligence',
    employee_count: 10,
    founded_year: '2024',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2329918, longitude: 72.8698902, is_hq: true },
    ],
  },
  {
    name: 'DL Minds',
    slug: 'dl-minds',
    website: 'https://dlminds.com',
    description: 'From Vision to Reality.',
    industry: 'Affiliate Marketing',
    employee_count: 10,
    founded_year: '2021',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2320551, longitude: 72.878352, is_hq: true },
    ],
  },
  {
    name: 'One.25 Tech & Design',
    slug: 'one-25-tech-design',
    website: 'https://one25techdesign.com/',
    description: 'Your One-Stop Solution for Graphic Design, Digital Marketing, Branding, Web & App Development, UI/UX and Printing.',
    industry: 'Graphic Design',
    employee_count: 10,
    founded_year: '2021',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2339447, longitude: 72.9130675, is_hq: true },
    ],
  },
  {
    name: 'Popway Software Pvt Ltd',
    slug: 'popway-software-pvt-ltd',
    website: 'https://www.popway.in',
    description: 'Surat-based IT firm with 15+ years of experience, offers web development, consulting, and software solutions for all needs.',
    industry: 'Custom Software Development',
    employee_count: 10,
    founded_year: '2009',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1845683, longitude: 72.8302575, is_hq: true },
    ],
  },
  {
    name: 'Techsoul Solutions',
    slug: 'techsoul-solutions',
    website: 'https://www.techsoulsolutions.com/',
    description: 'Techsoul Solutions builds scalable mobile apps, web platforms, and AI-powered products using modern technologies for startups and growing businesses.',
    industry: 'Mobile App Development',
    employee_count: 10,
    founded_year: '2023',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.235153, longitude: 72.8728245, is_hq: true },
    ],
  },
  {
    name: 'Team Unibrains',
    slug: 'team-unibrains',
    website: 'https://www.teamunibrains.com/',
    description: 'We deliver cost-effective, high-quality offshore web and mobile app development to deployment service, helping clients work efficiently.',
    industry: 'Web Development',
    employee_count: 10,
    founded_year: '2021',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2371184, longitude: 72.9093359, is_hq: true },
    ],
  },
  {
    name: 'Bitcoding Solutions',
    slug: 'bitcoding-solutions',
    website: 'https://bitcodingsolutions.com/',
    description: 'Best AI/ML & Python Development Company in Surat, India — Backend development, Web Scraping, App development, WordPress development, UI/UX Design.',
    industry: 'Artificial Intelligence',
    employee_count: 50,
    founded_year: '2020',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2316112, longitude: 72.8755536, is_hq: true },
    ],
  },
  {
    name: 'Vraj Technologies',
    slug: 'vraj-technologies',
    website: 'https://www.vrajtechnologies.com/',
    description: 'VRAJ Technologies provides web development, SEO, digital marketing, app development, and WhatsApp API solutions to grow businesses online.',
    industry: 'E-Commerce Development',
    employee_count: 2,
    founded_year: '2016',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1831199, longitude: 72.8718342, is_hq: true },
    ],
  },
  {
    name: 'Declone Labs Pvt Ltd',
    slug: 'declone-labs-pvt-ltd',
    website: 'https://declone.io/',
    description: 'Declone Labs is a React, Next.js & AI development company building scalable, high-performance digital products for global businesses.',
    industry: 'Web Development',
    employee_count: 10,
    founded_year: '2018',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1481451, longitude: 72.7602682, is_hq: true },
    ],
  },
  {
    name: 'Flexion Infotech Pvt Ltd',
    slug: 'flexion-infotech-pvt-ltd',
    website: 'https://flexioninfotech.com/',
    description: 'Flexion Infotech Pvt. Ltd. is a fast-growing software development and technology consulting agency headquartered at Surat, Gujarat, India.',
    industry: 'Mobile App Development',
    employee_count: 10,
    founded_year: '2021',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.238577, longitude: 72.870993, is_hq: true },
    ],
  },
  {
    name: 'ExeLance IT',
    slug: 'exelance-it',
    website: 'https://exelanceit.in/',
    description: 'Experts for your Innovations.',
    industry: 'Artificial Intelligence',
    employee_count: 50,
    founded_year: '2019',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.209118, longitude: 72.8506599, is_hq: true },
    ],
  },
  {
    name: 'Scaleteam Technologies Pvt.Ltd',
    slug: 'scaleteam-technologies-pvt-ltd',
    website: 'https://www.scale-team.com/',
    description: 'We are IT consultant and develop customized business software applications using top notch technologies. We Help Startups, Collaborate to Innovate.',
    industry: 'Mobile App Development',
    employee_count: 50,
    founded_year: '2016',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2362265, longitude: 72.8618014, is_hq: true },
    ],
  },
  {
    name: 'EbizzInfotech',
    slug: 'ebizzinfotech',
    website: 'https://www.ebizzinfotech.com/',
    description: 'If you can dream it, we can build it. Intelligent apps require brilliant design and intuitive product strategy.',
    industry: 'Mobile App Development',
    employee_count: 50,
    founded_year: '2012',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1948008, longitude: 72.8102247, is_hq: true },
    ],
  },
  {
    name: 'M-Square Technologies',
    slug: 'm-square-technologies',
    website: 'https://msquaretec.com/',
    description: 'With seven years of experience in web development and design, we have solidified our reputation as a trusted leader in our local market.',
    industry: 'Web Development',
    employee_count: 2,
    founded_year: '2017',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2114115, longitude: 72.8595689, is_hq: true },
    ],
  },
  {
    name: 'Shunyavkash',
    slug: 'shunyavkash',
    website: 'https://www.shunyavkash.com',
    description: 'Building Tomorrow\'s Digital Solutions, Today!',
    industry: 'Custom Software Development',
    employee_count: 10,
    founded_year: '2023',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2380155, longitude: 72.8879355, is_hq: true },
    ],
  },
  {
    name: 'RecurPost',
    slug: 'recurpost-social-media-scheduler-with-repeating-schedules',
    website: 'https://recurpost.com/',
    description: 'One Click, Share All Social Media Scheduler.',
    industry: 'Social Media Marketing',
    employee_count: 10,
    founded_year: '2015',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 33.9765053, longitude: -83.7434366, is_hq: true },
    ],
  },
  {
    name: 'DigiEn InfoSoft LLP',
    slug: 'digien-infosoft-llp',
    website: 'https://www.digien.in/',
    description: 'A tech company working on digitalization of enterprises.',
    industry: 'Custom Software Development',
    employee_count: 2,
    founded_year: '2017',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1828697, longitude: 72.827996, is_hq: true },
    ],
  },
  {
    name: 'MonkDA',
    slug: 'monkda',
    website: 'https://monkda.com/',
    description: 'Empowering Startups and Businesses to Grow and innovate with Technological Expertise.',
    industry: 'Mobile App Development',
    employee_count: 10,
    founded_year: '2018',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1507012, longitude: 72.7758668, is_hq: true },
    ],
  },
  {
    name: 'BRIGHTEN SOLUTIONS PVT LTD',
    slug: 'brighten-solutions-pvt-ltd',
    website: 'https://brightensolutions.com/',
    description: 'Custom Software & Websites That Scale with You from Surat, Gujarat.',
    industry: 'Custom Software Development',
    employee_count: 10,
    founded_year: '2016',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1410894, longitude: 72.7827906, is_hq: true },
    ],
  },
  {
    name: 'U & I Resources Pvt. Ltd',
    slug: 'u-i-resources-pvt-ltd',
    website: 'https://uandibrandsolutions.com/',
    description: 'U & I Resources Pvt. Ltd is one stop solution provider for your advertising, branding, marketing, events, exhibition & MICE needs, based in Surat.',
    industry: 'Advertising',
    employee_count: 10,
    founded_year: '2003',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1955148, longitude: 72.792691, is_hq: true },
    ],
  },
  {
    name: 'Limpid Systems',
    slug: 'limpid-systems',
    website: 'https://www.limpidsystems.com/',
    description: 'A software development company having expertise in web, app, custom software development, ecommerce, AI automation, and Chrome extension development.',
    industry: 'Web Development',
    employee_count: 10,
    founded_year: '2019',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.246646, longitude: 72.8902222, is_hq: true },
    ],
  },
  {
    name: 'VBS Global',
    slug: 'vbs-global',
    website: 'https://vbsglobal.co/',
    description: 'VBS Global offers outsourced bookkeeping, payroll, tax processing, and virtual CFO services for businesses in USA, UK & Australia.',
    industry: 'Finance & Accounting Outsourcing',
    employee_count: 50,
    founded_year: '2016',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2281405, longitude: 72.865786, is_hq: true },
    ],
  },
  {
    name: 'SEO Professionals',
    slug: 'seo-professionals',
    website: 'https://seoprofessionals.in/',
    description: 'Result Oriented Digital Marketing Agency.',
    industry: 'SEO',
    employee_count: 10,
    founded_year: '2008',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 40.266869, longitude: -47.8023207, is_hq: true },
    ],
  },
  {
    name: 'DashStack',
    slug: 'dashstack-infotech-ai-powered-cross-platform-full-stack-app-development',
    website: 'https://www.dashstack.tech/',
    description: 'We build scalable Flutter apps with AI, IoT, and cloud integrations to deliver high-performance cross-platform solutions.',
    industry: 'Mobile App Development',
    employee_count: 2,
    founded_year: '2022',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2302433, longitude: 72.8058015, is_hq: true },
    ],
  },
  {
    name: 'ADPenguin',
    slug: 'adpenguin',
    website: 'https://adpenguin.in/',
    description: 'AdPenguin is a digital marketing agency in Surat specializing in SEO, social media, and ads to boost brand visibility and drive business growth.',
    industry: 'SEO',
    employee_count: 2,
    founded_year: '2024',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1812291, longitude: 72.8285609, is_hq: true },
    ],
  },
  {
    name: 'Codeline Infotech LLP',
    slug: 'codeline-infotech-llp',
    website: 'https://www.codelineinfotech.com/',
    description: 'Innovative solutions for tomorrow\'s technology.',
    industry: 'Mobile App Development',
    employee_count: 10,
    founded_year: '2018',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2136852, longitude: 72.8851702, is_hq: true },
    ],
  },
  {
    name: 'Verloop Web',
    slug: 'verloop-web',
    website: 'https://verloopweb.com',
    description: 'Verloop Web - Web Development Company | SEO Services | Digital Marketing.',
    industry: 'Web Development',
    employee_count: 10,
    founded_year: '2013',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1506963, longitude: 72.773031, is_hq: true },
    ],
  },
  {
    name: 'Astha Technology Solutions Private Limited',
    slug: 'astha-technology-solutions-private-limited',
    website: 'https://asthatechnology.com',
    description: 'Astha Technology Solutions Pvt. Ltd. provides professional management with 13+ years of experience in Internet Marketing.',
    industry: 'Pay Per Click',
    employee_count: 10,
    founded_year: '2008',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2253468, longitude: 72.817052, is_hq: true },
    ],
  },
  {
    name: 'Qbits9',
    slug: 'qbits9',
    website: 'https://qbits9.com',
    description: 'Leading Technology Solutions.',
    industry: 'E-Commerce Development',
    employee_count: 10,
    founded_year: '2024',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2249103, longitude: 72.8070076, is_hq: true },
    ],
  },
  {
    name: 'SetBlue',
    slug: 'setblue',
    website: 'https://www.setblue.com/',
    description: 'Setting Brands Globally.',
    industry: 'E-Commerce Development',
    employee_count: 10,
    founded_year: '2004',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1843624, longitude: 72.8338928, is_hq: true },
    ],
  },
  {
    name: 'Codeyes Infotech',
    slug: 'codeyes-infotech',
    website: 'https://codeyesinfotech.com/',
    description: 'Codeyes offers top-notch software, mobile apps, website development, and CRM solutions to meet client needs.',
    industry: 'E-Commerce Development',
    employee_count: 10,
    founded_year: '2018',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.2393062, longitude: 72.911715, is_hq: true },
    ],
  },
  {
    name: 'Meritorious Global',
    slug: 'meritorious-global',
    website: 'https://meritorious.global',
    description: '8+ Years Experience — with years of experience and a team of highly skilled professionals.',
    industry: 'Mobile App Development',
    employee_count: 10,
    founded_year: '2016',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1894981, longitude: 72.8137448, is_hq: true },
    ],
  },
  {
    name: 'Sevlex Cybersecurity',
    slug: 'sevlex-cybersecurity',
    website: 'http://www.sevlex.com',
    description: 'Sevlex Cybersecurity has simplified security by creating 3 models for small grade business to enterprise grade, making it less complicated for SMBs.',
    industry: 'Cybersecurity',
    employee_count: 2,
    founded_year: '2025',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1955592, longitude: 72.8279709, is_hq: true },
    ],
  },
  {
    name: 'Tech Innovators',
    slug: 'tech-innovators-2',
    website: 'https://techinnovators.co.in',
    description: 'We are Innovators — One of the most Versatile Team on Planet. Technology In Our Expertise.',
    industry: 'Custom Software Development',
    employee_count: 10,
    founded_year: '2019',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1870034, longitude: 72.7858663, is_hq: true },
    ],
  },
  {
    name: 'Tracely Tag',
    slug: 'tracely-tag',
    website: 'https://www.tracelytag.com/',
    description: 'TracelyTag is a secure traceability and brand protection platform combining SaaS, IoT, and smart tagging to protect your supply chain.',
    industry: 'Web Development',
    employee_count: 10,
    founded_year: '2025',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1490384, longitude: 72.7758406, is_hq: true },
    ],
  },
  {
    name: 'SEODigitalBoost',
    slug: 'seodigitalboost',
    website: 'https://seodigitalboost.com/',
    description: 'SEODigitalBoost is a Digital Marketing Agency combining AI and data science to deliver faster rankings, higher organic traffic & real business growth.',
    industry: 'Advertising',
    employee_count: 2,
    founded_year: '2021',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1851435, longitude: 72.7838509, is_hq: true },
    ],
  },
  {
    name: 'Triveni Global Software Services LLP',
    slug: 'triveni-global-software-services-llp',
    website: 'https://triveniglobalsoft.com/',
    description: 'Creating a culture of Dedication, Passion & Goals.',
    industry: 'Web Development',
    employee_count: 50,
    founded_year: '2013',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.183242, longitude: 72.7836252, is_hq: true },
    ],
  },
  {
    name: 'Fortune Analytica',
    slug: 'fortune-analytica',
    website: 'https://fortuneanalytica.com/',
    description: '360-degree digital marketing agency in India.',
    industry: 'B2B Lead Generation',
    employee_count: 10,
    founded_year: '2020',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1474821, longitude: 72.7687505, is_hq: true },
    ],
  },
  {
    name: 'santhyaseo',
    slug: 'santhyaseo',
    website: 'https://www.santhyainfotech.com/',
    description: 'Santhya Infotech offers SEO, ads, and social media marketing solutions to help businesses grow online with measurable results and lasting impact.',
    industry: 'SEO',
    employee_count: 2,
    founded_year: '2024',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1765481, longitude: 72.8186837, is_hq: true },
    ],
  },
  {
    name: 'Cinesta - Video Production Company',
    slug: 'cinesta-video-production-company',
    website: 'https://cinesta.in/',
    description: 'Cinesta Video Production creates high-quality commercials and advertisements.',
    industry: 'Video Production',
    employee_count: 10,
    founded_year: '2017',
    offices: [
      { city: 'Surat', state: 'Gujarat', latitude: 21.1749662, longitude: 72.7816278, is_hq: true },
    ],
  },
  {
    name: 'Zoho',
    slug: 'zoho',
    website: 'https://zoho.com',
    description: 'Suite of 55+ business apps. Serves 100M+ users globally.',
    industry: 'SaaS',
    ats_platform: null,
    ats_identifier: null,
    employee_count: 15000,
    founded_year: '1996',
    offices: [
      { city: 'Surat', state: 'Gujarat', address: 'Vesu, Surat', latitude: 21.1553, longitude: 72.7732, is_hq: false },
    ],
  },
  {
    name: 'Adani Digital Labs',
    slug: 'adani-digital',
    website: 'https://adani.com',
    description: 'Technology arm of Adani Group building digital products for airports and logistics.',
    industry: 'Conglomerate Tech',
    ats_platform: null,
    ats_identifier: null,
    employee_count: 1500,
    founded_year: '2019',
    offices: [
      { city: 'Surat', state: 'Gujarat', address: 'Adani House, Navrangpura', latitude: 21.1950, longitude: 72.8240, is_hq: false },
    ],
  },
  {
    name: 'Navi Technologies',
    slug: 'navi',
    website: 'https://navi.com',
    description: 'Fintech company offering personal loans, home loans, insurance and mutual funds.',
    industry: 'Fintech',
    ats_platform: null,
    ats_identifier: null,
    employee_count: 700,
    founded_year: '2018',
    offices: [
      { city: 'Bangalore', state: 'Karnataka', address: 'Bellandur, Bangalore', latitude: 12.9250, longitude: 77.6745, is_hq: true },
    ],
  }
];

module.exports = companies;
